// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
// Options used:
//   * with "ritalin:parser/types@0.0.1" = "crate::wasi::parser_wasi::bindings::parser_types"
//   * with "ritalin:parser/syntaxes@0.0.1" = "crate::wasi::parser_wasi::bindings::syntax"
//   * default-bindings-module: "tolerant_parser_sdk::wasi::parser_wasi::bindings::parser_world"
//   * export-macro-name: export_parser
//   * pub-export-macro
use crate::wasi::parser_wasi::bindings::parser_types as __with_name0;
use crate::wasi::parser_wasi::bindings::syntax as __with_name1;
#[allow(dead_code, clippy::all)]
pub mod ritalin {
  pub mod parser {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod errors {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      
    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod ritalin {
    pub mod parser {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod parsers {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type SyntaxTree = super::super::super::super::__with_name1::SyntaxTree;
        pub type SyntaxTreeBorrow<'a> = super::super::super::super::__with_name1::SyntaxTreeBorrow<'a>;

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct Parser{
          handle: _rt::Resource<Parser>,
        }

        type _ParserRep<T> = Option<T>;

        impl Parser{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `Parser`.
          pub fn new<T: GuestParser>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _ParserRep<T> = Some(val);
            let ptr: *mut _ParserRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestParser>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestParser>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestParser>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestParser` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _ParserRep<T>) };
          }

          fn as_ptr<T: GuestParser>(&self) -> *mut _ParserRep<T> {
            Parser::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`Parser`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct ParserBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a Parser>,
        }

        impl<'a> ParserBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestParser>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _ParserRep<T> {
            Parser::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for Parser{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:parser/parsers@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]parser"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct IncrementalParser{
          handle: _rt::Resource<IncrementalParser>,
        }

        type _IncrementalParserRep<T> = Option<T>;

        impl IncrementalParser{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `IncrementalParser`.
          pub fn new<T: GuestIncrementalParser>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _IncrementalParserRep<T> = Some(val);
            let ptr: *mut _IncrementalParserRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestIncrementalParser>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestIncrementalParser>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestIncrementalParser>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestIncrementalParser` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _IncrementalParserRep<T>) };
          }

          fn as_ptr<T: GuestIncrementalParser>(&self) -> *mut _IncrementalParserRep<T> {
            IncrementalParser::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`IncrementalParser`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct IncrementalParserBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a IncrementalParser>,
        }

        impl<'a> IncrementalParserBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestIncrementalParser>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _IncrementalParserRep<T> {
            IncrementalParser::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for IncrementalParser{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:parser/parsers@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]incremental-parser"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct EditScope {
          /// editing start offset (UTF-16 code unit base)
          pub start_offset: u32,
          /// before editing length (UTF-16 code units)
          pub old_len: u32,
          /// after editing length (UTF-16 code units)
          pub new_len: u32,
        }
        impl ::core::fmt::Debug for EditScope {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("EditScope").field("start-offset", &self.start_offset).field("old-len", &self.old_len).field("new-len", &self.new_len).finish()
          }
        }
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_create_cabi<T: Guest>() -> i32 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          T::create()
        };
        (result0).take_handle() as i32
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_method_parser_parse_cabi<T: GuestParser>(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result1 = {
        let len0 = arg2;
        let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
        T::parse(ParserBorrow::lift(arg0 as u32 as usize).get(), _rt::string_lift(bytes0))
      };
      (result1).take_handle() as i32
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_method_parser_incremental_cabi<T: GuestParser>(arg0: *mut u8,arg1: i32,arg2: *mut u8,arg3: usize,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result1 = {
      let len0 = arg3;
      T::incremental(ParserBorrow::lift(arg0 as u32 as usize).get(), super::super::super::super::__with_name1::SyntaxTree::from_handle(arg1 as u32), _rt::Vec::from_raw_parts(arg2.cast(), len0, len0))
    };
    (result1).take_handle() as i32
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_method_incremental_parser_parse_cabi<T: GuestIncrementalParser>(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();let result1 = {
    let len0 = arg2;
    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
    T::parse(IncrementalParserBorrow::lift(arg0 as u32 as usize).get(), _rt::string_lift(bytes0))
  };
  (result1).take_handle() as i32
} }
pub trait Guest {
  type Parser: GuestParser;
  type IncrementalParser: GuestIncrementalParser;
  /// create new parser instance
  #[allow(async_fn_in_trait)]
  fn create() -> Parser;
}
pub trait GuestParser: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/parsers@0.0.1")]
    unsafe extern "C" {
      #[link_name = "[resource-new]parser"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/parsers@0.0.1")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]parser"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  /// execute to parse souce content
  #[allow(async_fn_in_trait)]
  fn parse(&self,source: _rt::String,) -> SyntaxTree;
  #[allow(async_fn_in_trait)]
  fn incremental(&self,tree: SyntaxTree,scopes: _rt::Vec::<EditScope>,) -> IncrementalParser;
}
pub trait GuestIncrementalParser: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/parsers@0.0.1")]
    unsafe extern "C" {
      #[link_name = "[resource-new]incremental-parser"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/parsers@0.0.1")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]incremental-parser"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  /// execute to parse souce content
  #[allow(async_fn_in_trait)]
  fn parse(&self,source: _rt::String,) -> SyntaxTree;
}
#[doc(hidden)]
#[macro_export]
macro_rules! __export_ritalin_parser_parsers_0_0_1_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "ritalin:parser/parsers@0.0.1#create")]
    unsafe extern "C" fn export_create() -> i32 {
      unsafe { $($path_to_types)*::_export_create_cabi::<$ty>() }
    }
    #[unsafe(export_name = "ritalin:parser/parsers@0.0.1#[method]parser.parse")]
    unsafe extern "C" fn export_method_parser_parse(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> i32 {
      unsafe { $($path_to_types)*::_export_method_parser_parse_cabi::<<$ty as $($path_to_types)*::Guest>::Parser>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "ritalin:parser/parsers@0.0.1#[method]parser.incremental")]
    unsafe extern "C" fn export_method_parser_incremental(arg0: *mut u8,arg1: i32,arg2: *mut u8,arg3: usize,) -> i32 {
      unsafe { $($path_to_types)*::_export_method_parser_incremental_cabi::<<$ty as $($path_to_types)*::Guest>::Parser>(arg0, arg1, arg2, arg3) }
    }
    #[unsafe(export_name = "ritalin:parser/parsers@0.0.1#[method]incremental-parser.parse")]
    unsafe extern "C" fn export_method_incremental_parser_parse(arg0: *mut u8,arg1: *mut u8,arg2: usize,) -> i32 {
      unsafe { $($path_to_types)*::_export_method_incremental_parser_parse_cabi::<<$ty as $($path_to_types)*::Guest>::IncrementalParser>(arg0, arg1, arg2) }
    }

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "ritalin:parser/parsers@0.0.1#[dtor]parser")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::Parser::dtor::<
          <$ty as $($path_to_types)*::Guest>::Parser
          >(rep)
        }
      }
    };
    

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "ritalin:parser/parsers@0.0.1#[dtor]incremental-parser")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::IncrementalParser::dtor::<
          <$ty as $($path_to_types)*::Guest>::IncrementalParser
          >(rep)
        }
      }
    };
    
  };);
}
#[doc(hidden)]
pub use __export_ritalin_parser_parsers_0_0_1_cabi;

}

}
}
}
mod _rt {
  #![allow(dead_code, clippy::all)]


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::boxed::Box;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub use alloc_crate::string::String;
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export_parser{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export_parser!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
#[macro_export]
macro_rules! __export_parser_world_impl {
  ($ty:ident) => (tolerant_parser_sdk::wasi::parser_wasi::bindings::parser_world::export_parser!($ty with_types_in tolerant_parser_sdk::wasi::parser_wasi::bindings::parser_world););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::ritalin::parser::parsers::__export_ritalin_parser_parsers_0_0_1_cabi!($ty with_types_in $($path_to_types_root)*::exports::ritalin::parser::parsers);
  const _: () = {

    #[cfg(target_arch = "wasm32")]
    #[unsafe(link_section = "component-type:wit-bindgen:0.42.1:ritalin:parser@0.0.1:parser-world:imports and exports")]
    #[doc(hidden)]
    #[allow(clippy::octal_escapes)]
    pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2508] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc9\x12\x01A\x02\x01\
A\x0d\x01B\x02\x01q\x01\x11node-build-failed\x01s\0\x04\0\x0bparse-error\x03\0\0\
\x03\0\x1britalin:parser/errors@0.0.1\x05\0\x01B\x08\x01m\x04\x07keyword\x0bnon-\
keyword\x07pattern\x0cnon-terminal\x04\0\x0csymbol-group\x03\0\0\x01r\x02\x04nam\
es\x05group\x01\x04\0\x0bsyntax-kind\x03\0\x02\x01m\x05\x04node\x09token-set\x0e\
leading-trivia\x0atoken-item\x0ftrailing-trivia\x04\0\x09node-type\x03\0\x04\x01\
m\x04\x04none\x06delete\x05shift\x07invalid\x04\0\x0cpatch-action\x03\0\x06\x04\0\
\x1aritalin:parser/types@0.0.1\x05\x01\x02\x03\0\x01\x0bsyntax-kind\x02\x03\0\x01\
\x09node-type\x02\x03\0\x01\x0cpatch-action\x01BJ\x02\x03\x02\x01\x02\x04\0\x0bs\
yntax-kind\x03\0\0\x02\x03\x02\x01\x03\x04\0\x09node-type\x03\0\x02\x02\x03\x02\x01\
\x04\x04\0\x0cpatch-action\x03\0\x04\x04\0\x0bsyntax-tree\x03\x01\x04\0\x0bsynta\
x-node\x03\x01\x04\0\x10syntax-token-set\x03\x01\x04\0\x11syntax-token-item\x03\x01\
\x01i\x07\x01i\x08\x01q\x02\x04node\x01\x0a\0\x09token-set\x01\x0b\0\x04\0\x0esy\
ntax-element\x03\0\x0c\x01r\x04\x04kind\x01\x06offsety\x03leny\x07is-leaf\x7f\x04\
\0\x0cmetadata-key\x03\0\x0e\x01r\x05\x09node-type\x03\x0aedit-statew\x05patch\x05\
\x0bchar-offsety\x08char-leny\x04\0\x08metadata\x03\0\x10\x01h\x06\x01@\x01\x04s\
elf\x12\0\x0a\x04\0\x18[method]syntax-tree.root\x01\x13\x01h\x07\x01@\x01\x04sel\
f\x14\0\x0f\x04\0\x20[method]syntax-node.metadata-key\x01\x15\x01@\x01\x04self\x14\
\0\x11\x04\0\x1c[method]syntax-node.metadata\x01\x16\x01k\x0a\x01@\x01\x04self\x14\
\0\x17\x04\0\x1a[method]syntax-node.parent\x01\x18\x01p\x0d\x01@\x01\x04self\x14\
\0\x19\x04\0\x1c[method]syntax-node.children\x01\x1a\x04\0$[method]syntax-node.d\
escendant-nodes\x01\x1a\x01i\x09\x01k\x1b\x01@\x02\x04self\x14\x06offsety\0\x1c\x04\
\0#[method]syntax-node.token-at-offset\x01\x1d\x01k\x0d\x01@\x01\x04self\x14\0\x1e\
\x04\0\x20[method]syntax-node.prev-sibling\x01\x1f\x04\0\x20[method]syntax-node.\
next-sibling\x01\x1f\x01h\x08\x01@\x01\x04self\x20\0\x0f\x04\0%[method]syntax-to\
ken-set.metadata-key\x01!\x01@\x01\x04self\x20\0\x11\x04\0![method]syntax-token-\
set.metadata\x01\"\x01@\x01\x04self\x20\0\x17\x04\0\x1f[method]syntax-token-set.\
parent\x01#\x01p\x1b\x01@\x01\x04self\x20\0$\x04\0*[method]syntax-token-set.desc\
endant-tokens\x01%\x01@\x01\x04self\x20\0\x1e\x04\0%[method]syntax-token-set.pre\
v-sibling\x01&\x04\0%[method]syntax-token-set.next-sibling\x01&\x04\0'[method]sy\
ntax-token-set.leading-trivia\x01%\x01@\x01\x04self\x20\0\x1b\x04\0\x1e[method]s\
yntax-token-set.token\x01'\x04\0([method]syntax-token-set.trailing-trivia\x01%\x01\
p\x01\x01@\x01\x04self\x20\0(\x04\0*[method]syntax-token-set.lookup-candidates\x01\
)\x01h\x09\x01@\x01\x04self*\0\x0f\x04\0&[method]syntax-token-item.metadata-key\x01\
+\x01@\x01\x04self*\0\x11\x04\0\"[method]syntax-token-item.metadata\x01,\x01k\x0b\
\x01@\x01\x04self*\0-\x04\0\x20[method]syntax-token-item.parent\x01.\x01@\x01\x04\
self*\0\x1c\x04\0$[method]syntax-token-item.prev-token\x01/\x04\0$[method]syntax\
-token-item.next-token\x01/\x01@\x01\x04self*\0s\x04\0\x1f[method]syntax-token-i\
tem.value\x010\x04\0\x1dritalin:parser/syntaxes@0.0.1\x05\x05\x02\x03\0\x02\x0bs\
yntax-tree\x02\x03\0\0\x0bparse-error\x01B\x16\x02\x03\x02\x01\x06\x04\0\x0bsynt\
ax-tree\x03\0\0\x02\x03\x02\x01\x07\x04\0\x0bparse-error\x03\0\x02\x04\0\x06pars\
er\x03\x01\x04\0\x12incremental-parser\x03\x01\x01r\x03\x0cstart-offsety\x07old-\
leny\x07new-leny\x04\0\x0aedit-scope\x03\0\x06\x01h\x04\x01i\x01\x01@\x02\x04sel\
f\x08\x06sources\0\x09\x04\0\x14[method]parser.parse\x01\x0a\x01p\x07\x01i\x05\x01\
@\x03\x04self\x08\x04tree\x09\x06scopes\x0b\0\x0c\x04\0\x1a[method]parser.increm\
ental\x01\x0d\x01h\x05\x01@\x02\x04self\x0e\x06sources\0\x09\x04\0\x20[method]in\
cremental-parser.parse\x01\x0f\x01i\x04\x01@\0\0\x10\x04\0\x06create\x01\x11\x04\
\0\x1critalin:parser/parsers@0.0.1\x05\x08\x04\0!ritalin:parser/parser-world@0.0\
.1\x04\0\x0b\x12\x01\0\x0cparser-world\x03\0\0\0G\x09producers\x01\x0cprocessed-\
by\x02\x0dwit-component\x070.234.0\x10wit-bindgen-rust\x060.42.1";
  };
  )
}
#[doc(inline)]
pub use __export_parser_world_impl as export_parser;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.42.1:ritalin:parser@0.0.1:parser-world-with-all-of-its-exports-removed:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 315] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x98\x01\x01A\x02\x01\
A\x02\x01B\x02\x01q\x01\x11node-build-failed\x01s\0\x04\0\x0bparse-error\x03\0\0\
\x03\0\x1britalin:parser/errors@0.0.1\x05\0\x04\0Aritalin:parser/parser-world-wi\
th-all-of-its-exports-removed@0.0.1\x04\0\x0b2\x01\0,parser-world-with-all-of-it\
s-exports-removed\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compone\
nt\x070.234.0\x10wit-bindgen-rust\x060.42.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

