// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
// Options used:
//   * with "ritalin:parser/types@0.3.1" = "crate::wasi::parser_wasi::bindings::parser_types"
//   * default-bindings-module: "crate::wasi::parser_wasi::bindings::syntax_tree_world"
use crate::wasi::parser_wasi::bindings::parser_types as __with_name0;
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod ritalin {
    pub mod parser {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod syntaxes {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type SyntaxKind = super::super::super::super::__with_name0::SyntaxKind;
        pub type NodeType = super::super::super::super::__with_name0::NodeType;
        pub type PatchAction = super::super::super::super::__with_name0::PatchAction;
        /// A syntax tree returned the parser

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct SyntaxTree{
          handle: _rt::Resource<SyntaxTree>,
        }

        type _SyntaxTreeRep<T> = Option<T>;

        impl SyntaxTree{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `SyntaxTree`.
          pub fn new<T: GuestSyntaxTree>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _SyntaxTreeRep<T> = Some(val);
            let ptr: *mut _SyntaxTreeRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestSyntaxTree>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestSyntaxTree>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestSyntaxTree>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestSyntaxTree` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _SyntaxTreeRep<T>) };
          }

          fn as_ptr<T: GuestSyntaxTree>(&self) -> *mut _SyntaxTreeRep<T> {
            SyntaxTree::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`SyntaxTree`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct SyntaxTreeBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a SyntaxTree>,
        }

        impl<'a> SyntaxTreeBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestSyntaxTree>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _SyntaxTreeRep<T> {
            SyntaxTree::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for SyntaxTree{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]syntax-tree"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        /// Syntax node is mainly Non-terminated symbol

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct SyntaxNode{
          handle: _rt::Resource<SyntaxNode>,
        }

        type _SyntaxNodeRep<T> = Option<T>;

        impl SyntaxNode{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `SyntaxNode`.
          pub fn new<T: GuestSyntaxNode>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _SyntaxNodeRep<T> = Some(val);
            let ptr: *mut _SyntaxNodeRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestSyntaxNode>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestSyntaxNode>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestSyntaxNode>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestSyntaxNode` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _SyntaxNodeRep<T>) };
          }

          fn as_ptr<T: GuestSyntaxNode>(&self) -> *mut _SyntaxNodeRep<T> {
            SyntaxNode::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`SyntaxNode`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct SyntaxNodeBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a SyntaxNode>,
        }

        impl<'a> SyntaxNodeBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestSyntaxNode>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _SyntaxNodeRep<T> {
            SyntaxNode::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for SyntaxNode{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]syntax-node"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        /// Token set is grouping token items

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct SyntaxTokenSet{
          handle: _rt::Resource<SyntaxTokenSet>,
        }

        type _SyntaxTokenSetRep<T> = Option<T>;

        impl SyntaxTokenSet{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `SyntaxTokenSet`.
          pub fn new<T: GuestSyntaxTokenSet>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _SyntaxTokenSetRep<T> = Some(val);
            let ptr: *mut _SyntaxTokenSetRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestSyntaxTokenSet>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestSyntaxTokenSet>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestSyntaxTokenSet>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestSyntaxTokenSet` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _SyntaxTokenSetRep<T>) };
          }

          fn as_ptr<T: GuestSyntaxTokenSet>(&self) -> *mut _SyntaxTokenSetRep<T> {
            SyntaxTokenSet::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`SyntaxTokenSet`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct SyntaxTokenSetBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a SyntaxTokenSet>,
        }

        impl<'a> SyntaxTokenSetBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestSyntaxTokenSet>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _SyntaxTokenSetRep<T> {
            SyntaxTokenSet::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for SyntaxTokenSet{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]syntax-token-set"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct SyntaxTokenItem{
          handle: _rt::Resource<SyntaxTokenItem>,
        }

        type _SyntaxTokenItemRep<T> = Option<T>;

        impl SyntaxTokenItem{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `SyntaxTokenItem`.
          pub fn new<T: GuestSyntaxTokenItem>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _SyntaxTokenItemRep<T> = Some(val);
            let ptr: *mut _SyntaxTokenItemRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestSyntaxTokenItem>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestSyntaxTokenItem>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestSyntaxTokenItem>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestSyntaxTokenItem` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _SyntaxTokenItemRep<T>) };
          }

          fn as_ptr<T: GuestSyntaxTokenItem>(&self) -> *mut _SyntaxTokenItemRep<T> {
            SyntaxTokenItem::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`SyntaxTokenItem`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct SyntaxTokenItemBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a SyntaxTokenItem>,
        }

        impl<'a> SyntaxTokenItemBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestSyntaxTokenItem>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _SyntaxTokenItemRep<T> {
            SyntaxTokenItem::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for SyntaxTokenItem{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]syntax-token-item"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        /// Children of node consists of the node or the token set
        pub enum SyntaxElement {
          Node(SyntaxNode),
          TokenSet(SyntaxTokenSet),
        }
        impl ::core::fmt::Debug for SyntaxElement {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              SyntaxElement::Node(e) => {
                f.debug_tuple("SyntaxElement::Node").field(e).finish()
              }
              SyntaxElement::TokenSet(e) => {
                f.debug_tuple("SyntaxElement::TokenSet").field(e).finish()
              }
            }
          }
        }
        #[derive(Clone)]
        pub struct MetadataKey {
          /// symbol kind of node
          pub kind: SyntaxKind,
          /// byte offset from begining of the document
          pub offset: u32,
          /// byte-length of node
          /// For the node and the token set, it's a summary of all descendant node
          pub len: u32,
          /// Wherther node is leaf (token item)
          pub is_leaf: bool,
        }
        impl ::core::fmt::Debug for MetadataKey {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("MetadataKey").field("kind", &self.kind).field("offset", &self.offset).field("len", &self.len).field("is-leaf", &self.is_leaf).finish()
          }
        }
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct Metadata {
          /// type of node
          pub node_type: NodeType,
          /// Resume state at incremental parsing
          pub edit_state: u64,
          /// Selected patch action
          /// If it does not go to error recover, `None` passed
          pub patch: PatchAction,
          /// char offset from begining of the document
          pub char_offset: u32,
          /// char length of node
          /// For the node and the token set, it's a summary of all descendant node
          pub char_len: u32,
        }
        impl ::core::fmt::Debug for Metadata {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Metadata").field("node-type", &self.node_type).field("edit-state", &self.edit_state).field("patch", &self.patch).field("char-offset", &self.char_offset).field("char-len", &self.char_len).finish()
          }
        }
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_method_syntax_tree_root_cabi<T: GuestSyntaxTree>(arg0: *mut u8,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          T::root(SyntaxTreeBorrow::lift(arg0 as u32 as usize).get())
        };
        (result0).take_handle() as i32
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_method_syntax_node_metadata_key_cabi<T: GuestSyntaxNode>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result0 = {
        T::metadata_key(SyntaxNodeBorrow::lift(arg0 as u32 as usize).get())
      };
      let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
      let MetadataKey{ kind:kind2, offset:offset2, len:len2, is_leaf:is_leaf2, } = result0;
      let super::super::super::super::__with_name0::SyntaxKind{ name:name3, group:group3, } = kind2;
      let vec4 = (name3.into_bytes()).into_boxed_slice();
      let ptr4 = vec4.as_ptr().cast::<u8>();
      let len4 = vec4.len();
      ::core::mem::forget(vec4);
      *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
      *ptr1.add(0).cast::<*mut u8>() = ptr4.cast_mut();
      *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group3.clone() as i32) as u8;
      *ptr1.add(3*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(offset2);
      *ptr1.add(4+3*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(len2);
      *ptr1.add(8+3*::core::mem::size_of::<*const u8>()).cast::<u8>() = (match is_leaf2 { true => 1, false => 0 }) as u8;
      ptr1
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_method_syntax_node_metadata_key<T: GuestSyntaxNode>(arg0: *mut u8,) { unsafe {
      let l0 = *arg0.add(0).cast::<*mut u8>();
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l0, l1, 1);
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_method_syntax_node_metadata_cabi<T: GuestSyntaxNode>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result0 = {
      T::metadata(SyntaxNodeBorrow::lift(arg0 as u32 as usize).get())
    };
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Metadata{ node_type:node_type2, edit_state:edit_state2, patch:patch2, char_offset:char_offset2, char_len:char_len2, } = result0;
    *ptr1.add(0).cast::<u8>() = (node_type2.clone() as i32) as u8;
    *ptr1.add(8).cast::<i64>() = _rt::as_i64(edit_state2);
    *ptr1.add(16).cast::<u8>() = (patch2.clone() as i32) as u8;
    *ptr1.add(20).cast::<i32>() = _rt::as_i32(char_offset2);
    *ptr1.add(24).cast::<i32>() = _rt::as_i32(char_len2);
    ptr1
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_method_syntax_node_parent_cabi<T: GuestSyntaxNode>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();let result0 = {
    T::parent(SyntaxNodeBorrow::lift(arg0 as u32 as usize).get())
  };
  let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
  match result0 {
    Some(e) => {
      *ptr1.add(0).cast::<u8>() = (1i32) as u8;
      *ptr1.add(4).cast::<i32>() = (e).take_handle() as i32;
    },
    None => {
      {
        *ptr1.add(0).cast::<u8>() = (0i32) as u8;
      }
    },
  };ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_node_children_cabi<T: GuestSyntaxNode>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::children(SyntaxNodeBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec2 = result0;
let len2 = vec2.len();
let layout2 = _rt::alloc::Layout::from_size_align(vec2.len() * 8, 4).unwrap();
let (result2, _cleanup2) = wit_bindgen::rt::Cleanup::new(layout2);if let Some(cleanup) = _cleanup2 { cleanup.forget(); }
for (i, e) in vec2.into_iter().enumerate() {
  let base = result2.add(i * 8);
  {
    match e {
      SyntaxElement::Node(e) => {
        *base.add(0).cast::<u8>() = (0i32) as u8;
        *base.add(4).cast::<i32>() = (e).take_handle() as i32;
      },
      SyntaxElement::TokenSet(e) => {
        *base.add(0).cast::<u8>() = (1i32) as u8;
        *base.add(4).cast::<i32>() = (e).take_handle() as i32;
      },
    }
  }
}
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
*ptr1.add(0).cast::<*mut u8>() = result2;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_node_children<T: GuestSyntaxNode>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  let base2 = l0;
  let len2 = l1;
  _rt::cabi_dealloc(base2, len2 * 8, 4);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_node_descendant_nodes_cabi<T: GuestSyntaxNode>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::descendant_nodes(SyntaxNodeBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec2 = result0;
let len2 = vec2.len();
let layout2 = _rt::alloc::Layout::from_size_align(vec2.len() * 8, 4).unwrap();
let (result2, _cleanup2) = wit_bindgen::rt::Cleanup::new(layout2);if let Some(cleanup) = _cleanup2 { cleanup.forget(); }
for (i, e) in vec2.into_iter().enumerate() {
  let base = result2.add(i * 8);
  {
    match e {
      SyntaxElement::Node(e) => {
        *base.add(0).cast::<u8>() = (0i32) as u8;
        *base.add(4).cast::<i32>() = (e).take_handle() as i32;
      },
      SyntaxElement::TokenSet(e) => {
        *base.add(0).cast::<u8>() = (1i32) as u8;
        *base.add(4).cast::<i32>() = (e).take_handle() as i32;
      },
    }
  }
}
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
*ptr1.add(0).cast::<*mut u8>() = result2;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_node_descendant_nodes<T: GuestSyntaxNode>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  let base2 = l0;
  let len2 = l1;
  _rt::cabi_dealloc(base2, len2 * 8, 4);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_node_token_at_offset_cabi<T: GuestSyntaxNode>(arg0: *mut u8,arg1: i32,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::token_at_offset(SyntaxNodeBorrow::lift(arg0 as u32 as usize).get(), arg1 as u32)
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    *ptr1.add(4).cast::<i32>() = (e).take_handle() as i32;
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_node_prev_sibling_cabi<T: GuestSyntaxNode>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::prev_sibling(SyntaxNodeBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    match e {
      SyntaxElement::Node(e) => {
        *ptr1.add(4).cast::<u8>() = (0i32) as u8;
        *ptr1.add(8).cast::<i32>() = (e).take_handle() as i32;
      },
      SyntaxElement::TokenSet(e) => {
        *ptr1.add(4).cast::<u8>() = (1i32) as u8;
        *ptr1.add(8).cast::<i32>() = (e).take_handle() as i32;
      },
    }
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_node_next_sibling_cabi<T: GuestSyntaxNode>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::next_sibling(SyntaxNodeBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    match e {
      SyntaxElement::Node(e) => {
        *ptr1.add(4).cast::<u8>() = (0i32) as u8;
        *ptr1.add(8).cast::<i32>() = (e).take_handle() as i32;
      },
      SyntaxElement::TokenSet(e) => {
        *ptr1.add(4).cast::<u8>() = (1i32) as u8;
        *ptr1.add(8).cast::<i32>() = (e).take_handle() as i32;
      },
    }
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_metadata_key_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::metadata_key(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let MetadataKey{ kind:kind2, offset:offset2, len:len2, is_leaf:is_leaf2, } = result0;
let super::super::super::super::__with_name0::SyntaxKind{ name:name3, group:group3, } = kind2;
let vec4 = (name3.into_bytes()).into_boxed_slice();
let ptr4 = vec4.as_ptr().cast::<u8>();
let len4 = vec4.len();
::core::mem::forget(vec4);
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
*ptr1.add(0).cast::<*mut u8>() = ptr4.cast_mut();
*ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group3.clone() as i32) as u8;
*ptr1.add(3*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(offset2);
*ptr1.add(4+3*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(len2);
*ptr1.add(8+3*::core::mem::size_of::<*const u8>()).cast::<u8>() = (match is_leaf2 { true => 1, false => 0 }) as u8;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_token_set_metadata_key<T: GuestSyntaxTokenSet>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  _rt::cabi_dealloc(l0, l1, 1);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_metadata_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::metadata(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let Metadata{ node_type:node_type2, edit_state:edit_state2, patch:patch2, char_offset:char_offset2, char_len:char_len2, } = result0;
*ptr1.add(0).cast::<u8>() = (node_type2.clone() as i32) as u8;
*ptr1.add(8).cast::<i64>() = _rt::as_i64(edit_state2);
*ptr1.add(16).cast::<u8>() = (patch2.clone() as i32) as u8;
*ptr1.add(20).cast::<i32>() = _rt::as_i32(char_offset2);
*ptr1.add(24).cast::<i32>() = _rt::as_i32(char_len2);
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_parent_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::parent(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    *ptr1.add(4).cast::<i32>() = (e).take_handle() as i32;
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_descendant_tokens_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::descendant_tokens(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec2 = result0;
let len2 = vec2.len();
let layout2 = _rt::alloc::Layout::from_size_align(vec2.len() * 4, 4).unwrap();
let (result2, _cleanup2) = wit_bindgen::rt::Cleanup::new(layout2);if let Some(cleanup) = _cleanup2 { cleanup.forget(); }
for (i, e) in vec2.into_iter().enumerate() {
  let base = result2.add(i * 4);
  {
    *base.add(0).cast::<i32>() = (e).take_handle() as i32;
  }
}
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
*ptr1.add(0).cast::<*mut u8>() = result2;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_token_set_descendant_tokens<T: GuestSyntaxTokenSet>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  let base2 = l0;
  let len2 = l1;
  _rt::cabi_dealloc(base2, len2 * 4, 4);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_prev_sibling_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::prev_sibling(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    match e {
      SyntaxElement::Node(e) => {
        *ptr1.add(4).cast::<u8>() = (0i32) as u8;
        *ptr1.add(8).cast::<i32>() = (e).take_handle() as i32;
      },
      SyntaxElement::TokenSet(e) => {
        *ptr1.add(4).cast::<u8>() = (1i32) as u8;
        *ptr1.add(8).cast::<i32>() = (e).take_handle() as i32;
      },
    }
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_next_sibling_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::next_sibling(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    match e {
      SyntaxElement::Node(e) => {
        *ptr1.add(4).cast::<u8>() = (0i32) as u8;
        *ptr1.add(8).cast::<i32>() = (e).take_handle() as i32;
      },
      SyntaxElement::TokenSet(e) => {
        *ptr1.add(4).cast::<u8>() = (1i32) as u8;
        *ptr1.add(8).cast::<i32>() = (e).take_handle() as i32;
      },
    }
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_leading_trivia_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::leading_trivia(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec2 = result0;
let len2 = vec2.len();
let layout2 = _rt::alloc::Layout::from_size_align(vec2.len() * 4, 4).unwrap();
let (result2, _cleanup2) = wit_bindgen::rt::Cleanup::new(layout2);if let Some(cleanup) = _cleanup2 { cleanup.forget(); }
for (i, e) in vec2.into_iter().enumerate() {
  let base = result2.add(i * 4);
  {
    *base.add(0).cast::<i32>() = (e).take_handle() as i32;
  }
}
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
*ptr1.add(0).cast::<*mut u8>() = result2;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_token_set_leading_trivia<T: GuestSyntaxTokenSet>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  let base2 = l0;
  let len2 = l1;
  _rt::cabi_dealloc(base2, len2 * 4, 4);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_token_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::token(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
(result0).take_handle() as i32
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_trailing_trivia_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::trailing_trivia(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec2 = result0;
let len2 = vec2.len();
let layout2 = _rt::alloc::Layout::from_size_align(vec2.len() * 4, 4).unwrap();
let (result2, _cleanup2) = wit_bindgen::rt::Cleanup::new(layout2);if let Some(cleanup) = _cleanup2 { cleanup.forget(); }
for (i, e) in vec2.into_iter().enumerate() {
  let base = result2.add(i * 4);
  {
    *base.add(0).cast::<i32>() = (e).take_handle() as i32;
  }
}
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
*ptr1.add(0).cast::<*mut u8>() = result2;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_token_set_trailing_trivia<T: GuestSyntaxTokenSet>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  let base2 = l0;
  let len2 = l1;
  _rt::cabi_dealloc(base2, len2 * 4, 4);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_set_lookup_candidates_cabi<T: GuestSyntaxTokenSet>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::lookup_candidates(SyntaxTokenSetBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec4 = result0;
let len4 = vec4.len();
let layout4 = _rt::alloc::Layout::from_size_align(vec4.len() * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
let (result4, _cleanup4) = wit_bindgen::rt::Cleanup::new(layout4);if let Some(cleanup) = _cleanup4 { cleanup.forget(); }
for (i, e) in vec4.into_iter().enumerate() {
  let base = result4.add(i * (3*::core::mem::size_of::<*const u8>()));
  {
    let super::super::super::super::__with_name0::SyntaxKind{ name:name2, group:group2, } = e;
    let vec3 = (name2.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    *base.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group2.clone() as i32) as u8;
  }
}
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
*ptr1.add(0).cast::<*mut u8>() = result4;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_token_set_lookup_candidates<T: GuestSyntaxTokenSet>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  let base4 = l0;
  let len4 = l1;
  for i in 0..len4 {
    let base = base4.add(i * (3*::core::mem::size_of::<*const u8>()));
    {
      let l2 = *base.add(0).cast::<*mut u8>();
      let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l2, l3, 1);
    }
  }
  _rt::cabi_dealloc(base4, len4 * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_item_metadata_key_cabi<T: GuestSyntaxTokenItem>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::metadata_key(SyntaxTokenItemBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let MetadataKey{ kind:kind2, offset:offset2, len:len2, is_leaf:is_leaf2, } = result0;
let super::super::super::super::__with_name0::SyntaxKind{ name:name3, group:group3, } = kind2;
let vec4 = (name3.into_bytes()).into_boxed_slice();
let ptr4 = vec4.as_ptr().cast::<u8>();
let len4 = vec4.len();
::core::mem::forget(vec4);
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
*ptr1.add(0).cast::<*mut u8>() = ptr4.cast_mut();
*ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group3.clone() as i32) as u8;
*ptr1.add(3*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(offset2);
*ptr1.add(4+3*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(len2);
*ptr1.add(8+3*::core::mem::size_of::<*const u8>()).cast::<u8>() = (match is_leaf2 { true => 1, false => 0 }) as u8;
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_token_item_metadata_key<T: GuestSyntaxTokenItem>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  _rt::cabi_dealloc(l0, l1, 1);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_item_metadata_cabi<T: GuestSyntaxTokenItem>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::metadata(SyntaxTokenItemBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let Metadata{ node_type:node_type2, edit_state:edit_state2, patch:patch2, char_offset:char_offset2, char_len:char_len2, } = result0;
*ptr1.add(0).cast::<u8>() = (node_type2.clone() as i32) as u8;
*ptr1.add(8).cast::<i64>() = _rt::as_i64(edit_state2);
*ptr1.add(16).cast::<u8>() = (patch2.clone() as i32) as u8;
*ptr1.add(20).cast::<i32>() = _rt::as_i32(char_offset2);
*ptr1.add(24).cast::<i32>() = _rt::as_i32(char_len2);
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_item_parent_cabi<T: GuestSyntaxTokenItem>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::parent(SyntaxTokenItemBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    *ptr1.add(4).cast::<i32>() = (e).take_handle() as i32;
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_item_prev_token_cabi<T: GuestSyntaxTokenItem>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::prev_token(SyntaxTokenItemBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    *ptr1.add(4).cast::<i32>() = (e).take_handle() as i32;
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_item_next_token_cabi<T: GuestSyntaxTokenItem>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::next_token(SyntaxTokenItemBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    *ptr1.add(4).cast::<i32>() = (e).take_handle() as i32;
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_syntax_token_item_value_cabi<T: GuestSyntaxTokenItem>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::value(SyntaxTokenItemBorrow::lift(arg0 as u32 as usize).get())
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec2 = (result0.into_bytes()).into_boxed_slice();
let ptr2 = vec2.as_ptr().cast::<u8>();
let len2 = vec2.len();
::core::mem::forget(vec2);
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
*ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_syntax_token_item_value<T: GuestSyntaxTokenItem>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  _rt::cabi_dealloc(l0, l1, 1);
} }
pub trait Guest {
  type SyntaxTree: GuestSyntaxTree;
  type SyntaxNode: GuestSyntaxNode;
  type SyntaxTokenSet: GuestSyntaxTokenSet;
  type SyntaxTokenItem: GuestSyntaxTokenItem;
}
pub trait GuestSyntaxTree: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
    unsafe extern "C" {
      #[link_name = "[resource-new]syntax-tree"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]syntax-tree"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  /// Root node
  #[allow(async_fn_in_trait)]
  fn root(&self,) -> SyntaxNode;
}
pub trait GuestSyntaxNode: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
    unsafe extern "C" {
      #[link_name = "[resource-new]syntax-node"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]syntax-node"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  /// Node metadata key
  #[allow(async_fn_in_trait)]
  fn metadata_key(&self,) -> MetadataKey;
  /// Node metadata value
  #[allow(async_fn_in_trait)]
  fn metadata(&self,) -> Metadata;
  /// parent node
  /// it will return none if not root node
  #[allow(async_fn_in_trait)]
  fn parent(&self,) -> Option<SyntaxNode>;
  /// enumerate all of the child nodes or the token-sets
  #[allow(async_fn_in_trait)]
  fn children(&self,) -> _rt::Vec::<SyntaxElement>;
  /// enumerate all of the descendant nodes or the token-sets containing self node
  #[allow(async_fn_in_trait)]
  fn descendant_nodes(&self,) -> _rt::Vec::<SyntaxElement>;
  /// look up a item of the syntax token set (UTF-16 code unit base)
  #[allow(async_fn_in_trait)]
  fn token_at_offset(&self,offset: u32,) -> Option<SyntaxTokenItem>;
  /// get previous neighbor sibling node on the same parent
  #[allow(async_fn_in_trait)]
  fn prev_sibling(&self,) -> Option<SyntaxElement>;
  /// get next neighbor sibling node on the same parent
  #[allow(async_fn_in_trait)]
  fn next_sibling(&self,) -> Option<SyntaxElement>;
}
pub trait GuestSyntaxTokenSet: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
    unsafe extern "C" {
      #[link_name = "[resource-new]syntax-token-set"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]syntax-token-set"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  /// Node metadata key
  #[allow(async_fn_in_trait)]
  fn metadata_key(&self,) -> MetadataKey;
  /// Node metadata value
  #[allow(async_fn_in_trait)]
  fn metadata(&self,) -> Metadata;
  /// parent node
  /// it will return none if not root node
  #[allow(async_fn_in_trait)]
  fn parent(&self,) -> Option<SyntaxNode>;
  /// enumerate all of the token items; leading trivia, main token, and trailing trivia
  #[allow(async_fn_in_trait)]
  fn descendant_tokens(&self,) -> _rt::Vec::<SyntaxTokenItem>;
  /// get previous neighbor sibling node on the same parent
  #[allow(async_fn_in_trait)]
  fn prev_sibling(&self,) -> Option<SyntaxElement>;
  /// get next neighbor sibling node on the same parent
  #[allow(async_fn_in_trait)]
  fn next_sibling(&self,) -> Option<SyntaxElement>;
  /// Returns leading trivia tokens
  #[allow(async_fn_in_trait)]
  fn leading_trivia(&self,) -> _rt::Vec::<SyntaxTokenItem>;
  /// Returns main token
  #[allow(async_fn_in_trait)]
  fn token(&self,) -> SyntaxTokenItem;
  /// returns trailing trivia tokens
  #[allow(async_fn_in_trait)]
  fn trailing_trivia(&self,) -> _rt::Vec::<SyntaxTokenItem>;
  /// Look up another candidate for specified node or token set
  #[allow(async_fn_in_trait)]
  fn lookup_candidates(&self,) -> _rt::Vec::<SyntaxKind>;
}
pub trait GuestSyntaxTokenItem: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
    unsafe extern "C" {
      #[link_name = "[resource-new]syntax-token-item"]
      fn new(_: *mut u8, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
    
    unsafe { new(val) as u32 }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "[export]ritalin:parser/syntaxes@0.3.1")]
    unsafe extern "C" {
      #[link_name = "[resource-rep]syntax-token-item"]
      fn rep(_: i32, ) -> *mut u8;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
    
    unsafe { rep(handle as i32) }
  }

  
  /// Node metadata key
  #[allow(async_fn_in_trait)]
  fn metadata_key(&self,) -> MetadataKey;
  /// Node metadata value
  #[allow(async_fn_in_trait)]
  fn metadata(&self,) -> Metadata;
  /// parent node
  /// it will return none if not root node
  #[allow(async_fn_in_trait)]
  fn parent(&self,) -> Option<SyntaxTokenSet>;
  /// get previous neighbor token over the parent node
  #[allow(async_fn_in_trait)]
  fn prev_token(&self,) -> Option<SyntaxTokenItem>;
  /// get next neighbor token over the parent node
  #[allow(async_fn_in_trait)]
  fn next_token(&self,) -> Option<SyntaxTokenItem>;
  /// Returns token value
  #[allow(async_fn_in_trait)]
  fn value(&self,) -> _rt::String;
}
#[doc(hidden)]

macro_rules! __export_ritalin_parser_syntaxes_0_3_1_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-tree.root")]
    unsafe extern "C" fn export_method_syntax_tree_root(arg0: *mut u8,) -> i32 {
      unsafe { $($path_to_types)*::_export_method_syntax_tree_root_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTree>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-node.metadata-key")]
    unsafe extern "C" fn export_method_syntax_node_metadata_key(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_node_metadata_key_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-node.metadata-key")]
    unsafe extern "C" fn _post_return_method_syntax_node_metadata_key(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_node_metadata_key::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-node.metadata")]
    unsafe extern "C" fn export_method_syntax_node_metadata(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_node_metadata_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-node.parent")]
    unsafe extern "C" fn export_method_syntax_node_parent(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_node_parent_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-node.children")]
    unsafe extern "C" fn export_method_syntax_node_children(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_node_children_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-node.children")]
    unsafe extern "C" fn _post_return_method_syntax_node_children(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_node_children::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-node.descendant-nodes")]
    unsafe extern "C" fn export_method_syntax_node_descendant_nodes(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_node_descendant_nodes_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-node.descendant-nodes")]
    unsafe extern "C" fn _post_return_method_syntax_node_descendant_nodes(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_node_descendant_nodes::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-node.token-at-offset")]
    unsafe extern "C" fn export_method_syntax_node_token_at_offset(arg0: *mut u8,arg1: i32,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_node_token_at_offset_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0, arg1) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-node.prev-sibling")]
    unsafe extern "C" fn export_method_syntax_node_prev_sibling(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_node_prev_sibling_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-node.next-sibling")]
    unsafe extern "C" fn export_method_syntax_node_next_sibling(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_node_next_sibling_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxNode>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.metadata-key")]
    unsafe extern "C" fn export_method_syntax_token_set_metadata_key(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_metadata_key_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.metadata-key")]
    unsafe extern "C" fn _post_return_method_syntax_token_set_metadata_key(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_token_set_metadata_key::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.metadata")]
    unsafe extern "C" fn export_method_syntax_token_set_metadata(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_metadata_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.parent")]
    unsafe extern "C" fn export_method_syntax_token_set_parent(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_parent_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.descendant-tokens")]
    unsafe extern "C" fn export_method_syntax_token_set_descendant_tokens(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_descendant_tokens_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.descendant-tokens")]
    unsafe extern "C" fn _post_return_method_syntax_token_set_descendant_tokens(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_token_set_descendant_tokens::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.prev-sibling")]
    unsafe extern "C" fn export_method_syntax_token_set_prev_sibling(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_prev_sibling_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.next-sibling")]
    unsafe extern "C" fn export_method_syntax_token_set_next_sibling(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_next_sibling_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.leading-trivia")]
    unsafe extern "C" fn export_method_syntax_token_set_leading_trivia(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_leading_trivia_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.leading-trivia")]
    unsafe extern "C" fn _post_return_method_syntax_token_set_leading_trivia(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_token_set_leading_trivia::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.token")]
    unsafe extern "C" fn export_method_syntax_token_set_token(arg0: *mut u8,) -> i32 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_token_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.trailing-trivia")]
    unsafe extern "C" fn export_method_syntax_token_set_trailing_trivia(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_trailing_trivia_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.trailing-trivia")]
    unsafe extern "C" fn _post_return_method_syntax_token_set_trailing_trivia(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_token_set_trailing_trivia::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.lookup-candidates")]
    unsafe extern "C" fn export_method_syntax_token_set_lookup_candidates(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_set_lookup_candidates_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-token-set.lookup-candidates")]
    unsafe extern "C" fn _post_return_method_syntax_token_set_lookup_candidates(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_token_set_lookup_candidates::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenSet>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-item.metadata-key")]
    unsafe extern "C" fn export_method_syntax_token_item_metadata_key(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_item_metadata_key_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenItem>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-token-item.metadata-key")]
    unsafe extern "C" fn _post_return_method_syntax_token_item_metadata_key(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_token_item_metadata_key::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenItem>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-item.metadata")]
    unsafe extern "C" fn export_method_syntax_token_item_metadata(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_item_metadata_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenItem>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-item.parent")]
    unsafe extern "C" fn export_method_syntax_token_item_parent(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_item_parent_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenItem>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-item.prev-token")]
    unsafe extern "C" fn export_method_syntax_token_item_prev_token(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_item_prev_token_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenItem>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-item.next-token")]
    unsafe extern "C" fn export_method_syntax_token_item_next_token(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_item_next_token_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenItem>(arg0) }
    }
    #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[method]syntax-token-item.value")]
    unsafe extern "C" fn export_method_syntax_token_item_value(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_syntax_token_item_value_cabi::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenItem>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_ritalin:parser/syntaxes@0.3.1#[method]syntax-token-item.value")]
    unsafe extern "C" fn _post_return_method_syntax_token_item_value(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_syntax_token_item_value::<<$ty as $($path_to_types)*::Guest>::SyntaxTokenItem>(arg0) }
    }

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[dtor]syntax-tree")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::SyntaxTree::dtor::<
          <$ty as $($path_to_types)*::Guest>::SyntaxTree
          >(rep)
        }
      }
    };
    

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[dtor]syntax-node")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::SyntaxNode::dtor::<
          <$ty as $($path_to_types)*::Guest>::SyntaxNode
          >(rep)
        }
      }
    };
    

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[dtor]syntax-token-set")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::SyntaxTokenSet::dtor::<
          <$ty as $($path_to_types)*::Guest>::SyntaxTokenSet
          >(rep)
        }
      }
    };
    

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "ritalin:parser/syntaxes@0.3.1#[dtor]syntax-token-item")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::SyntaxTokenItem::dtor::<
          <$ty as $($path_to_types)*::Guest>::SyntaxTokenItem
          >(rep)
        }
      }
    };
    
  };);
}
#[doc(hidden)]
pub(crate) use __export_ritalin_parser_syntaxes_0_3_1_cabi;

#[repr(align(8))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 24+2*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 24+2*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, clippy::all)]


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::boxed::Box;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  
  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  pub use alloc_crate::alloc;
  pub use alloc_crate::vec::Vec;
  pub use alloc_crate::string::String;
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_syntax_tree_world_impl {
  ($ty:ident) => (crate::wasi::parser_wasi::bindings::syntax_tree_world::export!($ty with_types_in crate::wasi::parser_wasi::bindings::syntax_tree_world););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::ritalin::parser::syntaxes::__export_ritalin_parser_syntaxes_0_3_1_cabi!($ty with_types_in $($path_to_types_root)*::exports::ritalin::parser::syntaxes);
  )
}
#[doc(inline)]
pub(crate) use __export_syntax_tree_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.42.1:ritalin:parser@0.3.1:syntax-tree-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2055] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xff\x0e\x01A\x02\x01\
A\x07\x01B\x08\x01m\x04\x07keyword\x0bnon-keyword\x07pattern\x0cnon-terminal\x04\
\0\x0csymbol-group\x03\0\0\x01r\x02\x04names\x05group\x01\x04\0\x0bsyntax-kind\x03\
\0\x02\x01m\x05\x04node\x09token-set\x0eleading-trivia\x0atoken-item\x0ftrailing\
-trivia\x04\0\x09node-type\x03\0\x04\x01m\x04\x04none\x06delete\x05shift\x07inva\
lid\x04\0\x0cpatch-action\x03\0\x06\x03\0\x1aritalin:parser/types@0.3.1\x05\0\x02\
\x03\0\0\x0bsyntax-kind\x02\x03\0\0\x09node-type\x02\x03\0\0\x0cpatch-action\x01\
BJ\x02\x03\x02\x01\x01\x04\0\x0bsyntax-kind\x03\0\0\x02\x03\x02\x01\x02\x04\0\x09\
node-type\x03\0\x02\x02\x03\x02\x01\x03\x04\0\x0cpatch-action\x03\0\x04\x04\0\x0b\
syntax-tree\x03\x01\x04\0\x0bsyntax-node\x03\x01\x04\0\x10syntax-token-set\x03\x01\
\x04\0\x11syntax-token-item\x03\x01\x01i\x07\x01i\x08\x01q\x02\x04node\x01\x0a\0\
\x09token-set\x01\x0b\0\x04\0\x0esyntax-element\x03\0\x0c\x01r\x04\x04kind\x01\x06\
offsety\x03leny\x07is-leaf\x7f\x04\0\x0cmetadata-key\x03\0\x0e\x01r\x05\x09node-\
type\x03\x0aedit-statew\x05patch\x05\x0bchar-offsety\x08char-leny\x04\0\x08metad\
ata\x03\0\x10\x01h\x06\x01@\x01\x04self\x12\0\x0a\x04\0\x18[method]syntax-tree.r\
oot\x01\x13\x01h\x07\x01@\x01\x04self\x14\0\x0f\x04\0\x20[method]syntax-node.met\
adata-key\x01\x15\x01@\x01\x04self\x14\0\x11\x04\0\x1c[method]syntax-node.metada\
ta\x01\x16\x01k\x0a\x01@\x01\x04self\x14\0\x17\x04\0\x1a[method]syntax-node.pare\
nt\x01\x18\x01p\x0d\x01@\x01\x04self\x14\0\x19\x04\0\x1c[method]syntax-node.chil\
dren\x01\x1a\x04\0$[method]syntax-node.descendant-nodes\x01\x1a\x01i\x09\x01k\x1b\
\x01@\x02\x04self\x14\x06offsety\0\x1c\x04\0#[method]syntax-node.token-at-offset\
\x01\x1d\x01k\x0d\x01@\x01\x04self\x14\0\x1e\x04\0\x20[method]syntax-node.prev-s\
ibling\x01\x1f\x04\0\x20[method]syntax-node.next-sibling\x01\x1f\x01h\x08\x01@\x01\
\x04self\x20\0\x0f\x04\0%[method]syntax-token-set.metadata-key\x01!\x01@\x01\x04\
self\x20\0\x11\x04\0![method]syntax-token-set.metadata\x01\"\x01@\x01\x04self\x20\
\0\x17\x04\0\x1f[method]syntax-token-set.parent\x01#\x01p\x1b\x01@\x01\x04self\x20\
\0$\x04\0*[method]syntax-token-set.descendant-tokens\x01%\x01@\x01\x04self\x20\0\
\x1e\x04\0%[method]syntax-token-set.prev-sibling\x01&\x04\0%[method]syntax-token\
-set.next-sibling\x01&\x04\0'[method]syntax-token-set.leading-trivia\x01%\x01@\x01\
\x04self\x20\0\x1b\x04\0\x1e[method]syntax-token-set.token\x01'\x04\0([method]sy\
ntax-token-set.trailing-trivia\x01%\x01p\x01\x01@\x01\x04self\x20\0(\x04\0*[meth\
od]syntax-token-set.lookup-candidates\x01)\x01h\x09\x01@\x01\x04self*\0\x0f\x04\0\
&[method]syntax-token-item.metadata-key\x01+\x01@\x01\x04self*\0\x11\x04\0\"[met\
hod]syntax-token-item.metadata\x01,\x01k\x0b\x01@\x01\x04self*\0-\x04\0\x20[meth\
od]syntax-token-item.parent\x01.\x01@\x01\x04self*\0\x1c\x04\0$[method]syntax-to\
ken-item.prev-token\x01/\x04\0$[method]syntax-token-item.next-token\x01/\x01@\x01\
\x04self*\0s\x04\0\x1f[method]syntax-token-item.value\x010\x04\0\x1dritalin:pars\
er/syntaxes@0.3.1\x05\x04\x04\0&ritalin:parser/syntax-tree-world@0.3.1\x04\0\x0b\
\x17\x01\0\x11syntax-tree-world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.234.0\x10wit-bindgen-rust\x060.42.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

