// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
// Options used:
//   * default-bindings-module: "crate::wasi::parser_wasi::bindings::types_world"
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod ritalin {
    pub mod parser {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod types {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum SymbolGroup {
          Keyword,
          NonKeyword,
          Pattern,
          NonTerminal,
        }
        impl ::core::fmt::Debug for SymbolGroup {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              SymbolGroup::Keyword => {
                f.debug_tuple("SymbolGroup::Keyword").finish()
              }
              SymbolGroup::NonKeyword => {
                f.debug_tuple("SymbolGroup::NonKeyword").finish()
              }
              SymbolGroup::Pattern => {
                f.debug_tuple("SymbolGroup::Pattern").finish()
              }
              SymbolGroup::NonTerminal => {
                f.debug_tuple("SymbolGroup::NonTerminal").finish()
              }
            }
          }
        }

        impl SymbolGroup{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> SymbolGroup{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => SymbolGroup::Keyword,
              1 => SymbolGroup::NonKeyword,
              2 => SymbolGroup::Pattern,
              3 => SymbolGroup::NonTerminal,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        /// Terminal/Non-terminal symbol definition
        #[derive(Clone)]
        pub struct SyntaxKind {
          /// symbol name
          pub name: _rt::String,
          /// symbol group category
          pub group: SymbolGroup,
        }
        impl ::core::fmt::Debug for SyntaxKind {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("SyntaxKind").field("name", &self.name).field("group", &self.group).finish()
          }
        }
        /// Syntax node type
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum NodeType {
          Node,
          /// node for owning leading trivias, token and trailing trivias
          TokenSet,
          /// leading trivia mainly has some comment
          LeadingTrivia,
          /// main token
          TokenItem,
          /// trailing trivia mainly has some white space
          TrailingTrivia,
        }
        impl ::core::fmt::Debug for NodeType {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              NodeType::Node => {
                f.debug_tuple("NodeType::Node").finish()
              }
              NodeType::TokenSet => {
                f.debug_tuple("NodeType::TokenSet").finish()
              }
              NodeType::LeadingTrivia => {
                f.debug_tuple("NodeType::LeadingTrivia").finish()
              }
              NodeType::TokenItem => {
                f.debug_tuple("NodeType::TokenItem").finish()
              }
              NodeType::TrailingTrivia => {
                f.debug_tuple("NodeType::TrailingTrivia").finish()
              }
            }
          }
        }

        impl NodeType{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> NodeType{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => NodeType::Node,
              1 => NodeType::TokenSet,
              2 => NodeType::LeadingTrivia,
              3 => NodeType::TokenItem,
              4 => NodeType::TrailingTrivia,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        /// error recovery type selected by a error recovery
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum PatchAction {
          /// no error recovery
          None,
          /// lookahead token is deleted
          Delete,
          /// Non-terminated symbol is inserted
          Shift,
          /// failed to error recovery
          Invalid,
        }
        impl ::core::fmt::Debug for PatchAction {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              PatchAction::None => {
                f.debug_tuple("PatchAction::None").finish()
              }
              PatchAction::Delete => {
                f.debug_tuple("PatchAction::Delete").finish()
              }
              PatchAction::Shift => {
                f.debug_tuple("PatchAction::Shift").finish()
              }
              PatchAction::Invalid => {
                f.debug_tuple("PatchAction::Invalid").finish()
              }
            }
          }
        }

        impl PatchAction{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> PatchAction{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => PatchAction::None,
              1 => PatchAction::Delete,
              2 => PatchAction::Shift,
              3 => PatchAction::Invalid,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        #[doc(hidden)]

        macro_rules! __export_ritalin_parser_types_0_1_0_cabi{
          ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

          };);
        }
        #[doc(hidden)]
        pub(crate) use __export_ritalin_parser_types_0_1_0_cabi;

      }

    }
  }
}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::string::String;
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_types_world_impl {
  ($ty:ident) => (crate::wasi::parser_wasi::bindings::types_world::export!($ty with_types_in crate::wasi::parser_wasi::bindings::types_world););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::ritalin::parser::types::__export_ritalin_parser_types_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::ritalin::parser::types);
  )
}
#[doc(inline)]
pub(crate) use __export_types_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.42.1:ritalin:parser@0.1.0:types-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 424] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa6\x02\x01A\x02\x01\
A\x02\x01B\x08\x01m\x04\x07keyword\x0bnon-keyword\x07pattern\x0cnon-terminal\x04\
\0\x0csymbol-group\x03\0\0\x01r\x02\x04names\x05group\x01\x04\0\x0bsyntax-kind\x03\
\0\x02\x01m\x05\x04node\x09token-set\x0eleading-trivia\x0atoken-item\x0ftrailing\
-trivia\x04\0\x09node-type\x03\0\x04\x01m\x04\x04none\x06delete\x05shift\x07inva\
lid\x04\0\x0cpatch-action\x03\0\x06\x04\0\x1aritalin:parser/types@0.1.0\x05\0\x04\
\0\x20ritalin:parser/types-world@0.1.0\x04\0\x0b\x11\x01\0\x0btypes-world\x03\0\0\
\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.234.0\x10wit-bind\
gen-rust\x060.42.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

