// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
// Options used:
//   * default-bindings-module: "crate::bindings::types_world"
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod ritalin {
    pub mod parser {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod types {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        /// Terminal/Non-terminal symbol definition
        #[derive(Clone)]
        pub struct SyntaxKind {
          /// symbol name
          pub name: _rt::String,
          /// wether this is a keyword symbol
          pub is_keyword: bool,
          /// whether this is a terminal symbol
          pub is_terminal: bool,
        }
        impl ::core::fmt::Debug for SyntaxKind {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("SyntaxKind").field("name", &self.name).field("is-keyword", &self.is_keyword).field("is-terminal", &self.is_terminal).finish()
          }
        }
        /// Syntax node type
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum NodeType {
          Node,
          /// node for owning leading trivias, token and trailing trivias
          TokenSet,
          /// leading trivia mainly has some comment
          LeadingTrivia,
          /// main token
          TokenItem,
          /// trailing trivia mainly has some white space
          TrailingTrivia,
          /// node for supplied by the error recovery process
          Error,
          /// if a error recovery process failed, this node is inserted insted
          FatalError,
        }
        impl ::core::fmt::Debug for NodeType {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              NodeType::Node => {
                f.debug_tuple("NodeType::Node").finish()
              }
              NodeType::TokenSet => {
                f.debug_tuple("NodeType::TokenSet").finish()
              }
              NodeType::LeadingTrivia => {
                f.debug_tuple("NodeType::LeadingTrivia").finish()
              }
              NodeType::TokenItem => {
                f.debug_tuple("NodeType::TokenItem").finish()
              }
              NodeType::TrailingTrivia => {
                f.debug_tuple("NodeType::TrailingTrivia").finish()
              }
              NodeType::Error => {
                f.debug_tuple("NodeType::Error").finish()
              }
              NodeType::FatalError => {
                f.debug_tuple("NodeType::FatalError").finish()
              }
            }
          }
        }

        impl NodeType{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> NodeType{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => NodeType::Node,
              1 => NodeType::TokenSet,
              2 => NodeType::LeadingTrivia,
              3 => NodeType::TokenItem,
              4 => NodeType::TrailingTrivia,
              5 => NodeType::Error,
              6 => NodeType::FatalError,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        /// error recovery type selected by a error recovery
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum Recovery {
          /// lookahead token is deleted
          Delete,
          /// Non-terminated symbol is inserted
          Shift,
        }
        impl ::core::fmt::Debug for Recovery {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              Recovery::Delete => {
                f.debug_tuple("Recovery::Delete").finish()
              }
              Recovery::Shift => {
                f.debug_tuple("Recovery::Shift").finish()
              }
            }
          }
        }

        impl Recovery{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> Recovery{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => Recovery::Delete,
              1 => Recovery::Shift,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        #[doc(hidden)]

        macro_rules! __export_ritalin_parser_types_0_0_1_cabi{
          ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

          };);
        }
        #[doc(hidden)]
        pub(crate) use __export_ritalin_parser_types_0_0_1_cabi;

      }

    }
  }
}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::string::String;
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_types_world_impl {
  ($ty:ident) => (crate::bindings::types_world::export!($ty with_types_in crate::bindings::types_world););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::ritalin::parser::types::__export_ritalin_parser_types_0_0_1_cabi!($ty with_types_in $($path_to_types_root)*::exports::ritalin::parser::types);
  )
}
#[doc(inline)]
pub(crate) use __export_types_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.42.1:ritalin:parser@0.0.1:types-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 381] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfb\x01\x01A\x02\x01\
A\x02\x01B\x06\x01r\x03\x04names\x0ais-keyword\x7f\x0bis-terminal\x7f\x04\0\x0bs\
yntax-kind\x03\0\0\x01m\x07\x04node\x09token-set\x0eleading-trivia\x0atoken-item\
\x0ftrailing-trivia\x05error\x0bfatal-error\x04\0\x09node-type\x03\0\x02\x01m\x02\
\x06delete\x05shift\x04\0\x08recovery\x03\0\x04\x04\0\x1aritalin:parser/types@0.\
0.1\x05\0\x04\0\x20ritalin:parser/types-world@0.0.1\x04\0\x0b\x11\x01\0\x0btypes\
-world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.230\
.0\x10wit-bindgen-rust\x060.42.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

