// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
// Options used:
//   * with "ritalin:parser/types@0.3.1" = "crate::wasi::parser_wasi::bindings::parser_types"
//   * default-bindings-module: "tolerant_parser_sdk::wasi::event_capture_wasi::bindings::event_capture_world"
//   * export-macro-name: export_capture
//   * pub-export-macro
use crate::wasi::parser_wasi::bindings::parser_types as __with_name0;
use crate::wasi::parser_wasi::bindings::parser_types as __with_name1;
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod ritalin {
    pub mod event_capture {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod types {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type SyntaxKind = super::super::super::super::__with_name1::SyntaxKind;
        #[derive(Clone)]
        pub struct ScanEvent {
          /// Identifier for distinguishing token.
          pub kind: SyntaxKind,
          /// potion (byte offset) from a document head
          pub offset: u64,
          /// token length
          pub len: u64,
          /// token value
          pub value: Option<_rt::String>,
        }
        impl ::core::fmt::Debug for ScanEvent {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("ScanEvent").field("kind", &self.kind).field("offset", &self.offset).field("len", &self.len).field("value", &self.value).finish()
          }
        }
        #[derive(Clone)]
        pub struct Token {
          pub leading_trivia: _rt::Vec::<ScanEvent>,
          pub main_token: ScanEvent,
          pub trailing_trivia: _rt::Vec::<ScanEvent>,
        }
        impl ::core::fmt::Debug for Token {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Token").field("leading-trivia", &self.leading_trivia).field("main-token", &self.main_token).field("trailing-trivia", &self.trailing_trivia).finish()
          }
        }
        #[derive(Clone)]
        pub struct TransitionState {
          pub kind: SyntaxKind,
          pub current: Option<u64>,
          pub next: Option<u64>,
          pub edit: u64,
        }
        impl ::core::fmt::Debug for TransitionState {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("TransitionState").field("kind", &self.kind).field("current", &self.current).field("next", &self.next).field("edit", &self.edit).finish()
          }
        }
        #[derive(Clone)]
        pub struct ReduceTransitionState {
          pub kind: SyntaxKind,
          pub current: Option<u64>,
          pub next: Option<u64>,
          pub edit: u64,
          pub pop_count: u64,
        }
        impl ::core::fmt::Debug for ReduceTransitionState {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("ReduceTransitionState").field("kind", &self.kind).field("current", &self.current).field("next", &self.next).field("edit", &self.edit).field("pop-count", &self.pop_count).finish()
          }
        }
        #[derive(Clone)]
        pub enum ParseEvent {
          Shift(TransitionState),
          Reduce(ReduceTransitionState),
          Emit(TransitionState),
          Accept(TransitionState),
          PatchDrop(TransitionState),
          PatchShift(TransitionState),
          PatchReduce(ReduceTransitionState),
          PatchEmit(TransitionState),
          Invalid(TransitionState),
          InvalidEmit(ReduceTransitionState),
        }
        impl ::core::fmt::Debug for ParseEvent {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              ParseEvent::Shift(e) => {
                f.debug_tuple("ParseEvent::Shift").field(e).finish()
              }
              ParseEvent::Reduce(e) => {
                f.debug_tuple("ParseEvent::Reduce").field(e).finish()
              }
              ParseEvent::Emit(e) => {
                f.debug_tuple("ParseEvent::Emit").field(e).finish()
              }
              ParseEvent::Accept(e) => {
                f.debug_tuple("ParseEvent::Accept").field(e).finish()
              }
              ParseEvent::PatchDrop(e) => {
                f.debug_tuple("ParseEvent::PatchDrop").field(e).finish()
              }
              ParseEvent::PatchShift(e) => {
                f.debug_tuple("ParseEvent::PatchShift").field(e).finish()
              }
              ParseEvent::PatchReduce(e) => {
                f.debug_tuple("ParseEvent::PatchReduce").field(e).finish()
              }
              ParseEvent::PatchEmit(e) => {
                f.debug_tuple("ParseEvent::PatchEmit").field(e).finish()
              }
              ParseEvent::Invalid(e) => {
                f.debug_tuple("ParseEvent::Invalid").field(e).finish()
              }
              ParseEvent::InvalidEmit(e) => {
                f.debug_tuple("ParseEvent::InvalidEmit").field(e).finish()
              }
            }
          }
        }
        #[derive(Clone)]
        pub enum CaptureEvent {
          Scan(Token),
          Parse(ParseEvent),
        }
        impl ::core::fmt::Debug for CaptureEvent {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              CaptureEvent::Scan(e) => {
                f.debug_tuple("CaptureEvent::Scan").field(e).finish()
              }
              CaptureEvent::Parse(e) => {
                f.debug_tuple("CaptureEvent::Parse").field(e).finish()
              }
            }
          }
        }
        #[repr(C)]
        #[derive(Clone, Copy)]
        pub struct CaptureConfig {
          pub no_scan: bool,
          pub no_parse: bool,
          pub ignore_case: bool,
        }
        impl ::core::fmt::Debug for CaptureConfig {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("CaptureConfig").field("no-scan", &self.no_scan).field("no-parse", &self.no_parse).field("ignore-case", &self.ignore_case).finish()
          }
        }
        #[doc(hidden)]
        #[macro_export]
        macro_rules! __export_ritalin_event_capture_types_0_0_1_cabi{
          ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

          };);
        }
        #[doc(hidden)]
        pub use __export_ritalin_event_capture_types_0_0_1_cabi;

      }


      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod captures {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type CaptureEvent = super::super::super::super::exports::ritalin::event_capture::types::CaptureEvent;
        pub type CaptureConfig = super::super::super::super::exports::ritalin::event_capture::types::CaptureConfig;

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct EventCapture{
          handle: _rt::Resource<EventCapture>,
        }

        type _EventCaptureRep<T> = Option<T>;

        impl EventCapture{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `EventCapture`.
          pub fn new<T: GuestEventCapture>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _EventCaptureRep<T> = Some(val);
            let ptr: *mut _EventCaptureRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestEventCapture>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestEventCapture>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestEventCapture>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestEventCapture` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _EventCaptureRep<T>) };
          }

          fn as_ptr<T: GuestEventCapture>(&self) -> *mut _EventCaptureRep<T> {
            EventCapture::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`EventCapture`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct EventCaptureBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a EventCapture>,
        }

        impl<'a> EventCaptureBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestEventCapture>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _EventCaptureRep<T> {
            EventCapture::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for EventCapture{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:event-capture/captures@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]event-capture"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_create_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: i32,arg3: i32,arg4: i32,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result1 = {
          let len0 = arg1;
          let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
          T::create(_rt::string_lift(bytes0), super::super::super::super::exports::ritalin::event_capture::types::CaptureConfig{
            no_scan: _rt::bool_lift(arg2 as u8),
            no_parse: _rt::bool_lift(arg3 as u8),
            ignore_case: _rt::bool_lift(arg4 as u8),
          })
        };
        (result1).take_handle() as i32
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_method_event_capture_next_cabi<T: GuestEventCapture>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result0 = {
        T::next(EventCaptureBorrow::lift(arg0 as u32 as usize).get())
      };
      let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result0 {
        Some(e) => {
          *ptr1.add(0).cast::<u8>() = (1i32) as u8;
          use super::super::super::super::exports::ritalin::event_capture::types::CaptureEvent as V48;
          match e {
            V48::Scan(e) => {
              *ptr1.add(8).cast::<u8>() = (0i32) as u8;
              let super::super::super::super::exports::ritalin::event_capture::types::Token{ leading_trivia:leading_trivia2, main_token:main_token2, trailing_trivia:trailing_trivia2, } = e;
              let vec7 = leading_trivia2;
              let len7 = vec7.len();
              let layout7 = _rt::alloc::Layout::from_size_align(vec7.len() * (32+4*::core::mem::size_of::<*const u8>()), 8).unwrap();
              let (result7, _cleanup7) = wit_bindgen::rt::Cleanup::new(layout7);if let Some(cleanup) = _cleanup7 { cleanup.forget(); }
              for (i, e) in vec7.into_iter().enumerate() {
                let base = result7.add(i * (32+4*::core::mem::size_of::<*const u8>()));
                {
                  let super::super::super::super::exports::ritalin::event_capture::types::ScanEvent{ kind:kind3, offset:offset3, len:len3, value:value3, } = e;
                  let super::super::super::super::__with_name1::SyntaxKind{ name:name4, group:group4, } = kind3;
                  let vec5 = (name4.into_bytes()).into_boxed_slice();
                  let ptr5 = vec5.as_ptr().cast::<u8>();
                  let len5 = vec5.len();
                  ::core::mem::forget(vec5);
                  *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                  *base.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                  *base.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group4.clone() as i32) as u8;
                  *base.add(8+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(offset3);
                  *base.add(16+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(len3);
                  match value3 {
                    Some(e) => {
                      *base.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                      let vec6 = (e.into_bytes()).into_boxed_slice();
                      let ptr6 = vec6.as_ptr().cast::<u8>();
                      let len6 = vec6.len();
                      ::core::mem::forget(vec6);
                      *base.add(24+4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                      *base.add(24+3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6.cast_mut();
                    },
                    None => {
                      {
                        *base.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                      }
                    },
                  };}
                }
                *ptr1.add(16+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                *ptr1.add(16).cast::<*mut u8>() = result7;
                let super::super::super::super::exports::ritalin::event_capture::types::ScanEvent{ kind:kind8, offset:offset8, len:len8, value:value8, } = main_token2;
                let super::super::super::super::__with_name1::SyntaxKind{ name:name9, group:group9, } = kind8;
                let vec10 = (name9.into_bytes()).into_boxed_slice();
                let ptr10 = vec10.as_ptr().cast::<u8>();
                let len10 = vec10.len();
                ::core::mem::forget(vec10);
                *ptr1.add(16+3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len10;
                *ptr1.add(16+2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr10.cast_mut();
                *ptr1.add(16+4*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group9.clone() as i32) as u8;
                *ptr1.add(24+4*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(offset8);
                *ptr1.add(32+4*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(len8);
                match value8 {
                  Some(e) => {
                    *ptr1.add(40+4*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                    let vec11 = (e.into_bytes()).into_boxed_slice();
                    let ptr11 = vec11.as_ptr().cast::<u8>();
                    let len11 = vec11.len();
                    ::core::mem::forget(vec11);
                    *ptr1.add(40+6*::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
                    *ptr1.add(40+5*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr11.cast_mut();
                  },
                  None => {
                    {
                      *ptr1.add(40+4*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                    }
                  },
                };let vec16 = trailing_trivia2;
                let len16 = vec16.len();
                let layout16 = _rt::alloc::Layout::from_size_align(vec16.len() * (32+4*::core::mem::size_of::<*const u8>()), 8).unwrap();
                let (result16, _cleanup16) = wit_bindgen::rt::Cleanup::new(layout16);if let Some(cleanup) = _cleanup16 { cleanup.forget(); }
                for (i, e) in vec16.into_iter().enumerate() {
                  let base = result16.add(i * (32+4*::core::mem::size_of::<*const u8>()));
                  {
                    let super::super::super::super::exports::ritalin::event_capture::types::ScanEvent{ kind:kind12, offset:offset12, len:len12, value:value12, } = e;
                    let super::super::super::super::__with_name1::SyntaxKind{ name:name13, group:group13, } = kind12;
                    let vec14 = (name13.into_bytes()).into_boxed_slice();
                    let ptr14 = vec14.as_ptr().cast::<u8>();
                    let len14 = vec14.len();
                    ::core::mem::forget(vec14);
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
                    *base.add(0).cast::<*mut u8>() = ptr14.cast_mut();
                    *base.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group13.clone() as i32) as u8;
                    *base.add(8+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(offset12);
                    *base.add(16+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(len12);
                    match value12 {
                      Some(e) => {
                        *base.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                        let vec15 = (e.into_bytes()).into_boxed_slice();
                        let ptr15 = vec15.as_ptr().cast::<u8>();
                        let len15 = vec15.len();
                        ::core::mem::forget(vec15);
                        *base.add(24+4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
                        *base.add(24+3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr15.cast_mut();
                      },
                      None => {
                        {
                          *base.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                        }
                      },
                    };}
                  }
                  *ptr1.add(48+7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
                  *ptr1.add(48+6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result16;
                },
                V48::Parse(e) => {
                  *ptr1.add(8).cast::<u8>() = (1i32) as u8;
                  use super::super::super::super::exports::ritalin::event_capture::types::ParseEvent as V47;
                  match e {
                    V47::Shift(e) => {
                      *ptr1.add(16).cast::<u8>() = (0i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::TransitionState{ kind:kind17, current:current17, next:next17, edit:edit17, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name18, group:group18, } = kind17;
                      let vec19 = (name18.into_bytes()).into_boxed_slice();
                      let ptr19 = vec19.as_ptr().cast::<u8>();
                      let len19 = vec19.len();
                      ::core::mem::forget(vec19);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
                      *ptr1.add(24).cast::<*mut u8>() = ptr19.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group18.clone() as i32) as u8;
                      match current17 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next17 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit17);
                    },
                    V47::Reduce(e) => {
                      *ptr1.add(16).cast::<u8>() = (1i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::ReduceTransitionState{ kind:kind20, current:current20, next:next20, edit:edit20, pop_count:pop_count20, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name21, group:group21, } = kind20;
                      let vec22 = (name21.into_bytes()).into_boxed_slice();
                      let ptr22 = vec22.as_ptr().cast::<u8>();
                      let len22 = vec22.len();
                      ::core::mem::forget(vec22);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len22;
                      *ptr1.add(24).cast::<*mut u8>() = ptr22.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group21.clone() as i32) as u8;
                      match current20 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next20 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit20);
                      *ptr1.add(72+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(pop_count20);
                    },
                    V47::Emit(e) => {
                      *ptr1.add(16).cast::<u8>() = (2i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::TransitionState{ kind:kind23, current:current23, next:next23, edit:edit23, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name24, group:group24, } = kind23;
                      let vec25 = (name24.into_bytes()).into_boxed_slice();
                      let ptr25 = vec25.as_ptr().cast::<u8>();
                      let len25 = vec25.len();
                      ::core::mem::forget(vec25);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len25;
                      *ptr1.add(24).cast::<*mut u8>() = ptr25.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group24.clone() as i32) as u8;
                      match current23 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next23 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit23);
                    },
                    V47::Accept(e) => {
                      *ptr1.add(16).cast::<u8>() = (3i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::TransitionState{ kind:kind26, current:current26, next:next26, edit:edit26, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name27, group:group27, } = kind26;
                      let vec28 = (name27.into_bytes()).into_boxed_slice();
                      let ptr28 = vec28.as_ptr().cast::<u8>();
                      let len28 = vec28.len();
                      ::core::mem::forget(vec28);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len28;
                      *ptr1.add(24).cast::<*mut u8>() = ptr28.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group27.clone() as i32) as u8;
                      match current26 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next26 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit26);
                    },
                    V47::PatchDrop(e) => {
                      *ptr1.add(16).cast::<u8>() = (4i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::TransitionState{ kind:kind29, current:current29, next:next29, edit:edit29, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name30, group:group30, } = kind29;
                      let vec31 = (name30.into_bytes()).into_boxed_slice();
                      let ptr31 = vec31.as_ptr().cast::<u8>();
                      let len31 = vec31.len();
                      ::core::mem::forget(vec31);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len31;
                      *ptr1.add(24).cast::<*mut u8>() = ptr31.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group30.clone() as i32) as u8;
                      match current29 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next29 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit29);
                    },
                    V47::PatchShift(e) => {
                      *ptr1.add(16).cast::<u8>() = (5i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::TransitionState{ kind:kind32, current:current32, next:next32, edit:edit32, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name33, group:group33, } = kind32;
                      let vec34 = (name33.into_bytes()).into_boxed_slice();
                      let ptr34 = vec34.as_ptr().cast::<u8>();
                      let len34 = vec34.len();
                      ::core::mem::forget(vec34);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len34;
                      *ptr1.add(24).cast::<*mut u8>() = ptr34.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group33.clone() as i32) as u8;
                      match current32 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next32 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit32);
                    },
                    V47::PatchReduce(e) => {
                      *ptr1.add(16).cast::<u8>() = (6i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::ReduceTransitionState{ kind:kind35, current:current35, next:next35, edit:edit35, pop_count:pop_count35, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name36, group:group36, } = kind35;
                      let vec37 = (name36.into_bytes()).into_boxed_slice();
                      let ptr37 = vec37.as_ptr().cast::<u8>();
                      let len37 = vec37.len();
                      ::core::mem::forget(vec37);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len37;
                      *ptr1.add(24).cast::<*mut u8>() = ptr37.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group36.clone() as i32) as u8;
                      match current35 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next35 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit35);
                      *ptr1.add(72+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(pop_count35);
                    },
                    V47::PatchEmit(e) => {
                      *ptr1.add(16).cast::<u8>() = (7i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::TransitionState{ kind:kind38, current:current38, next:next38, edit:edit38, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name39, group:group39, } = kind38;
                      let vec40 = (name39.into_bytes()).into_boxed_slice();
                      let ptr40 = vec40.as_ptr().cast::<u8>();
                      let len40 = vec40.len();
                      ::core::mem::forget(vec40);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len40;
                      *ptr1.add(24).cast::<*mut u8>() = ptr40.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group39.clone() as i32) as u8;
                      match current38 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next38 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit38);
                    },
                    V47::Invalid(e) => {
                      *ptr1.add(16).cast::<u8>() = (8i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::TransitionState{ kind:kind41, current:current41, next:next41, edit:edit41, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name42, group:group42, } = kind41;
                      let vec43 = (name42.into_bytes()).into_boxed_slice();
                      let ptr43 = vec43.as_ptr().cast::<u8>();
                      let len43 = vec43.len();
                      ::core::mem::forget(vec43);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len43;
                      *ptr1.add(24).cast::<*mut u8>() = ptr43.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group42.clone() as i32) as u8;
                      match current41 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next41 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit41);
                    },
                    V47::InvalidEmit(e) => {
                      *ptr1.add(16).cast::<u8>() = (9i32) as u8;
                      let super::super::super::super::exports::ritalin::event_capture::types::ReduceTransitionState{ kind:kind44, current:current44, next:next44, edit:edit44, pop_count:pop_count44, } = e;
                      let super::super::super::super::__with_name1::SyntaxKind{ name:name45, group:group45, } = kind44;
                      let vec46 = (name45.into_bytes()).into_boxed_slice();
                      let ptr46 = vec46.as_ptr().cast::<u8>();
                      let len46 = vec46.len();
                      ::core::mem::forget(vec46);
                      *ptr1.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len46;
                      *ptr1.add(24).cast::<*mut u8>() = ptr46.cast_mut();
                      *ptr1.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (group45.clone() as i32) as u8;
                      match current44 {
                        Some(e) => {
                          *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(40+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(32+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };match next44 {
                        Some(e) => {
                          *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                          *ptr1.add(56+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(e);
                        },
                        None => {
                          {
                            *ptr1.add(48+2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                          }
                        },
                      };*ptr1.add(64+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(edit44);
                      *ptr1.add(72+2*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(pop_count44);
                    },
                  }
                },
              }
            },
            None => {
              {
                *ptr1.add(0).cast::<u8>() = (0i32) as u8;
              }
            },
          };ptr1
        } }
        #[doc(hidden)]
        #[allow(non_snake_case)]
        pub unsafe fn __post_return_method_event_capture_next<T: GuestEventCapture>(arg0: *mut u8,) { unsafe {
          let l0 = i32::from(*arg0.add(0).cast::<u8>());
          match l0 {
            0 => (),
            _ => {
              let l1 = i32::from(*arg0.add(8).cast::<u8>());
              match l1 {
                0 => {
                  let l2 = *arg0.add(16).cast::<*mut u8>();
                  let l3 = *arg0.add(16+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base9 = l2;
                  let len9 = l3;
                  for i in 0..len9 {
                    let base = base9.add(i * (32+4*::core::mem::size_of::<*const u8>()));
                    {
                      let l4 = *base.add(0).cast::<*mut u8>();
                      let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l4, l5, 1);
                      let l6 = i32::from(*base.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>());
                      match l6 {
                        0 => (),
                        _ => {
                          let l7 = *base.add(24+3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                          let l8 = *base.add(24+4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                          _rt::cabi_dealloc(l7, l8, 1);
                        },
                      }
                    }
                  }
                  _rt::cabi_dealloc(base9, len9 * (32+4*::core::mem::size_of::<*const u8>()), 8);
                  let l10 = *arg0.add(16+2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l11 = *arg0.add(16+3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  _rt::cabi_dealloc(l10, l11, 1);
                  let l12 = i32::from(*arg0.add(40+4*::core::mem::size_of::<*const u8>()).cast::<u8>());
                  match l12 {
                    0 => (),
                    _ => {
                      let l13 = *arg0.add(40+5*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l14 = *arg0.add(40+6*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l13, l14, 1);
                    },
                  }
                  let l15 = *arg0.add(48+6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l16 = *arg0.add(48+7*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base22 = l15;
                  let len22 = l16;
                  for i in 0..len22 {
                    let base = base22.add(i * (32+4*::core::mem::size_of::<*const u8>()));
                    {
                      let l17 = *base.add(0).cast::<*mut u8>();
                      let l18 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l17, l18, 1);
                      let l19 = i32::from(*base.add(24+2*::core::mem::size_of::<*const u8>()).cast::<u8>());
                      match l19 {
                        0 => (),
                        _ => {
                          let l20 = *base.add(24+3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                          let l21 = *base.add(24+4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                          _rt::cabi_dealloc(l20, l21, 1);
                        },
                      }
                    }
                  }
                  _rt::cabi_dealloc(base22, len22 * (32+4*::core::mem::size_of::<*const u8>()), 8);
                },
                _ => {
                  let l23 = i32::from(*arg0.add(16).cast::<u8>());
                  match l23 {
                    0 => {
                      let l24 = *arg0.add(24).cast::<*mut u8>();
                      let l25 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l24, l25, 1);
                    },
                    1 => {
                      let l26 = *arg0.add(24).cast::<*mut u8>();
                      let l27 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l26, l27, 1);
                    },
                    2 => {
                      let l28 = *arg0.add(24).cast::<*mut u8>();
                      let l29 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l28, l29, 1);
                    },
                    3 => {
                      let l30 = *arg0.add(24).cast::<*mut u8>();
                      let l31 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l30, l31, 1);
                    },
                    4 => {
                      let l32 = *arg0.add(24).cast::<*mut u8>();
                      let l33 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l32, l33, 1);
                    },
                    5 => {
                      let l34 = *arg0.add(24).cast::<*mut u8>();
                      let l35 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l34, l35, 1);
                    },
                    6 => {
                      let l36 = *arg0.add(24).cast::<*mut u8>();
                      let l37 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l36, l37, 1);
                    },
                    7 => {
                      let l38 = *arg0.add(24).cast::<*mut u8>();
                      let l39 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l38, l39, 1);
                    },
                    8 => {
                      let l40 = *arg0.add(24).cast::<*mut u8>();
                      let l41 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l40, l41, 1);
                    },
                    _ => {
                      let l42 = *arg0.add(24).cast::<*mut u8>();
                      let l43 = *arg0.add(24+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l42, l43, 1);
                    },
                  }
                },
              }
            },
          }
        } }
        pub trait Guest {
          type EventCapture: GuestEventCapture;
          #[allow(async_fn_in_trait)]
          fn create(source: _rt::String,config: CaptureConfig,) -> EventCapture;
        }
        pub trait GuestEventCapture: 'static {

          #[doc(hidden)]
          unsafe fn _resource_new(val: *mut u8) -> u32
          where Self: Sized
          {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:event-capture/captures@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[resource-new]event-capture"]
              fn new(_: *mut u8, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
            
            unsafe { new(val) as u32 }
          }

          #[doc(hidden)]
          fn _resource_rep(handle: u32) -> *mut u8
          where Self: Sized
          {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ritalin:event-capture/captures@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[resource-rep]event-capture"]
              fn rep(_: i32, ) -> *mut u8;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
            
            unsafe { rep(handle as i32) }
          }

          
          #[allow(async_fn_in_trait)]
          fn next(&self,) -> Option<CaptureEvent>;
        }
        #[doc(hidden)]
        #[macro_export]
        macro_rules! __export_ritalin_event_capture_captures_0_0_1_cabi{
          ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

            #[unsafe(export_name = "ritalin:event-capture/captures@0.0.1#create")]
            unsafe extern "C" fn export_create(arg0: *mut u8,arg1: usize,arg2: i32,arg3: i32,arg4: i32,) -> i32 {
              unsafe { $($path_to_types)*::_export_create_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4) }
            }
            #[unsafe(export_name = "ritalin:event-capture/captures@0.0.1#[method]event-capture.next")]
            unsafe extern "C" fn export_method_event_capture_next(arg0: *mut u8,) -> *mut u8 {
              unsafe { $($path_to_types)*::_export_method_event_capture_next_cabi::<<$ty as $($path_to_types)*::Guest>::EventCapture>(arg0) }
            }
            #[unsafe(export_name = "cabi_post_ritalin:event-capture/captures@0.0.1#[method]event-capture.next")]
            unsafe extern "C" fn _post_return_method_event_capture_next(arg0: *mut u8,) {
              unsafe { $($path_to_types)*::__post_return_method_event_capture_next::<<$ty as $($path_to_types)*::Guest>::EventCapture>(arg0) }
            }

            const _: () = {
              #[doc(hidden)]
              #[unsafe(export_name = "ritalin:event-capture/captures@0.0.1#[dtor]event-capture")]
              #[allow(non_snake_case)]
              unsafe extern "C" fn dtor(rep: *mut u8) {
                unsafe {
                  $($path_to_types)*::EventCapture::dtor::<
                  <$ty as $($path_to_types)*::Guest>::EventCapture
                  >(rep)
                }
              }
            };
            
          };);
        }
        #[doc(hidden)]
        pub use __export_ritalin_event_capture_captures_0_0_1_cabi;

        #[repr(align(8))]
        struct _RetArea([::core::mem::MaybeUninit::<u8>; 64+6*::core::mem::size_of::<*const u8>()]);
        static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 64+6*::core::mem::size_of::<*const u8>()]);

      }

    }
  }
}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::boxed::Box;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn bool_lift(val: u8) -> bool {
    if cfg!(debug_assertions) {
      match val {
        0 => false,
        1 => true,
        _ => panic!("invalid bool discriminant"),
      }
    } else {
      val != 0
    }
  }
  
  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  pub use alloc_crate::alloc;
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export_capture{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export_capture!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
#[macro_export]
macro_rules! __export_event_capture_world_impl {
  ($ty:ident) => (tolerant_parser_sdk::wasi::event_capture_wasi::bindings::event_capture_world::export_capture!($ty with_types_in tolerant_parser_sdk::wasi::event_capture_wasi::bindings::event_capture_world););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::ritalin::event_capture::types::__export_ritalin_event_capture_types_0_0_1_cabi!($ty with_types_in $($path_to_types_root)*::exports::ritalin::event_capture::types);
  $($path_to_types_root)*::exports::ritalin::event_capture::captures::__export_ritalin_event_capture_captures_0_0_1_cabi!($ty with_types_in $($path_to_types_root)*::exports::ritalin::event_capture::captures);
  const _: () = {

    #[cfg(target_arch = "wasm32")]
    #[unsafe(link_section = "component-type:wit-bindgen:0.42.1:ritalin:event-capture@0.0.1:event-capture-world:imports and exports")]
    #[doc(hidden)]
    #[allow(clippy::octal_escapes)]
    pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1480] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xbe\x0a\x01A\x02\x01\
A\x0b\x01B\x08\x01m\x04\x07keyword\x0bnon-keyword\x07pattern\x0cnon-terminal\x04\
\0\x0csymbol-group\x03\0\0\x01r\x02\x04names\x05group\x01\x04\0\x0bsyntax-kind\x03\
\0\x02\x01m\x05\x04node\x09token-set\x0eleading-trivia\x0atoken-item\x0ftrailing\
-trivia\x04\0\x09node-type\x03\0\x04\x01m\x04\x04none\x06delete\x05shift\x07inva\
lid\x04\0\x0cpatch-action\x03\0\x06\x03\0\x1aritalin:parser/types@0.3.1\x05\0\x01\
B\x08\x01m\x04\x07keyword\x0bnon-keyword\x07pattern\x0cnon-terminal\x04\0\x0csym\
bol-group\x03\0\0\x01r\x02\x04names\x05group\x01\x04\0\x0bsyntax-kind\x03\0\x02\x01\
m\x05\x04node\x09token-set\x0eleading-trivia\x0atoken-item\x0ftrailing-trivia\x04\
\0\x09node-type\x03\0\x04\x01m\x04\x04none\x06delete\x05shift\x07invalid\x04\0\x0c\
patch-action\x03\0\x06\x04\0\x1aritalin:parser/types@0.3.1\x05\x01\x02\x03\0\x01\
\x0bsyntax-kind\x01B\x13\x02\x03\x02\x01\x02\x04\0\x0bsyntax-kind\x03\0\0\x01ks\x01\
r\x04\x04kind\x01\x06offsetw\x03lenw\x05value\x02\x04\0\x0ascan-event\x03\0\x03\x01\
p\x04\x01r\x03\x0eleading-trivia\x05\x0amain-token\x04\x0ftrailing-trivia\x05\x04\
\0\x05token\x03\0\x06\x01kw\x01r\x04\x04kind\x01\x07current\x08\x04next\x08\x04e\
ditw\x04\0\x10transition-state\x03\0\x09\x01r\x05\x04kind\x01\x07current\x08\x04\
next\x08\x04editw\x09pop-countw\x04\0\x17reduce-transition-state\x03\0\x0b\x01q\x0a\
\x05shift\x01\x0a\0\x06reduce\x01\x0c\0\x04emit\x01\x0a\0\x06accept\x01\x0a\0\x0a\
patch-drop\x01\x0a\0\x0bpatch-shift\x01\x0a\0\x0cpatch-reduce\x01\x0c\0\x0apatch\
-emit\x01\x0a\0\x07invalid\x01\x0a\0\x0cinvalid-emit\x01\x0c\0\x04\0\x0bparse-ev\
ent\x03\0\x0d\x01q\x02\x04scan\x01\x07\0\x05parse\x01\x0e\0\x04\0\x0dcapture-eve\
nt\x03\0\x0f\x01r\x03\x07no-scan\x7f\x08no-parse\x7f\x0bignore-case\x7f\x04\0\x0e\
capture-config\x03\0\x11\x04\0!ritalin:event-capture/types@0.0.1\x05\x03\x02\x03\
\0\x02\x0dcapture-event\x02\x03\0\x02\x0ecapture-config\x01B\x0c\x02\x03\x02\x01\
\x04\x04\0\x0dcapture-event\x03\0\0\x02\x03\x02\x01\x05\x04\0\x0ecapture-config\x03\
\0\x02\x04\0\x0devent-capture\x03\x01\x01h\x04\x01k\x01\x01@\x01\x04self\x05\0\x06\
\x04\0\x1a[method]event-capture.next\x01\x07\x01i\x04\x01@\x02\x06sources\x06con\
fig\x03\0\x08\x04\0\x06create\x01\x09\x04\0$ritalin:event-capture/captures@0.0.1\
\x05\x06\x04\0/ritalin:event-capture/event-capture-world@0.0.1\x04\0\x0b\x19\x01\
\0\x13event-capture-world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit\
-component\x070.234.0\x10wit-bindgen-rust\x060.42.1";
  };
  )
}
#[doc(inline)]
pub use __export_event_capture_world_impl as export_capture;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.42.1:ritalin:event-capture@0.0.1:event-capture-world-with-all-of-its-exports-removed:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 511] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd5\x02\x01A\x02\x01\
A\x02\x01B\x08\x01m\x04\x07keyword\x0bnon-keyword\x07pattern\x0cnon-terminal\x04\
\0\x0csymbol-group\x03\0\0\x01r\x02\x04names\x05group\x01\x04\0\x0bsyntax-kind\x03\
\0\x02\x01m\x05\x04node\x09token-set\x0eleading-trivia\x0atoken-item\x0ftrailing\
-trivia\x04\0\x09node-type\x03\0\x04\x01m\x04\x04none\x06delete\x05shift\x07inva\
lid\x04\0\x0cpatch-action\x03\0\x06\x03\0\x1aritalin:parser/types@0.3.1\x05\0\x04\
\0Oritalin:event-capture/event-capture-world-with-all-of-its-exports-removed@0.0\
.1\x04\0\x0b9\x01\03event-capture-world-with-all-of-its-exports-removed\x03\0\0\0\
G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.234.0\x10wit-bindge\
n-rust\x060.42.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

