pub mod syntax_kind {
  use engine_core::SyntaxKind;
  # [allow (non_upper_case_globals)] pub static r#input : SyntaxKind = SyntaxKind { text : "input" , id : 1u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#cmdlist : SyntaxKind = SyntaxKind { text : "cmdlist" , id : 2u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#ecmd : SyntaxKind = SyntaxKind { text : "ecmd" , id : 3u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#SEMI : SyntaxKind = SyntaxKind { text : "SEMI" , id : 4u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#cmdx : SyntaxKind = SyntaxKind { text : "cmdx" , id : 5u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#explain : SyntaxKind = SyntaxKind { text : "explain" , id : 6u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#EXPLAIN : SyntaxKind = SyntaxKind { text : "EXPLAIN" , id : 7u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#QUERY : SyntaxKind = SyntaxKind { text : "QUERY" , id : 8u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#PLAN : SyntaxKind = SyntaxKind { text : "PLAN" , id : 9u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#cmd : SyntaxKind = SyntaxKind { text : "cmd" , id : 10u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#BEGIN : SyntaxKind = SyntaxKind { text : "BEGIN" , id : 11u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#transtype : SyntaxKind = SyntaxKind { text : "transtype" , id : 12u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#trans_opt : SyntaxKind = SyntaxKind { text : "trans_opt" , id : 13u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#TRANSACTION : SyntaxKind = SyntaxKind { text : "TRANSACTION" , id : 14u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#nm : SyntaxKind = SyntaxKind { text : "nm" , id : 15u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#DEFERRED : SyntaxKind = SyntaxKind { text : "DEFERRED" , id : 16u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#IMMEDIATE : SyntaxKind = SyntaxKind { text : "IMMEDIATE" , id : 17u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#EXCLUSIVE : SyntaxKind = SyntaxKind { text : "EXCLUSIVE" , id : 18u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#COMMIT : SyntaxKind = SyntaxKind { text : "COMMIT" , id : 19u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#END : SyntaxKind = SyntaxKind { text : "END" , id : 20u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ROLLBACK : SyntaxKind = SyntaxKind { text : "ROLLBACK" , id : 21u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#savepoint_opt : SyntaxKind = SyntaxKind { text : "savepoint_opt" , id : 22u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#SAVEPOINT : SyntaxKind = SyntaxKind { text : "SAVEPOINT" , id : 23u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#RELEASE : SyntaxKind = SyntaxKind { text : "RELEASE" , id : 24u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#TO : SyntaxKind = SyntaxKind { text : "TO" , id : 25u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#create_table : SyntaxKind = SyntaxKind { text : "create_table" , id : 26u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#create_table_args : SyntaxKind = SyntaxKind { text : "create_table_args" , id : 27u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#createkw : SyntaxKind = SyntaxKind { text : "createkw" , id : 28u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#temp : SyntaxKind = SyntaxKind { text : "temp" , id : 29u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#TABLE : SyntaxKind = SyntaxKind { text : "TABLE" , id : 30u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ifnotexists : SyntaxKind = SyntaxKind { text : "ifnotexists" , id : 31u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#dbnm : SyntaxKind = SyntaxKind { text : "dbnm" , id : 32u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#CREATE : SyntaxKind = SyntaxKind { text : "CREATE" , id : 33u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#IF : SyntaxKind = SyntaxKind { text : "IF" , id : 34u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#NOT : SyntaxKind = SyntaxKind { text : "NOT" , id : 35u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#EXISTS : SyntaxKind = SyntaxKind { text : "EXISTS" , id : 36u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#TEMP : SyntaxKind = SyntaxKind { text : "TEMP" , id : 37u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#LP : SyntaxKind = SyntaxKind { text : "LP" , id : 38u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#columnlist : SyntaxKind = SyntaxKind { text : "columnlist" , id : 39u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#conslist_opt : SyntaxKind = SyntaxKind { text : "conslist_opt" , id : 40u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#RP : SyntaxKind = SyntaxKind { text : "RP" , id : 41u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#table_option_set : SyntaxKind = SyntaxKind { text : "table_option_set" , id : 42u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#AS : SyntaxKind = SyntaxKind { text : "AS" , id : 43u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#select : SyntaxKind = SyntaxKind { text : "select" , id : 44u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#table_option : SyntaxKind = SyntaxKind { text : "table_option" , id : 45u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#COMMA : SyntaxKind = SyntaxKind { text : "COMMA" , id : 46u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#WITHOUT : SyntaxKind = SyntaxKind { text : "WITHOUT" , id : 47u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#columnname : SyntaxKind = SyntaxKind { text : "columnname" , id : 48u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#carglist : SyntaxKind = SyntaxKind { text : "carglist" , id : 49u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#typetoken : SyntaxKind = SyntaxKind { text : "typetoken" , id : 50u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#ABORT : SyntaxKind = SyntaxKind { text : "ABORT" , id : 51u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ACTION : SyntaxKind = SyntaxKind { text : "ACTION" , id : 52u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#AFTER : SyntaxKind = SyntaxKind { text : "AFTER" , id : 53u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ANALYZE : SyntaxKind = SyntaxKind { text : "ANALYZE" , id : 54u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ASC : SyntaxKind = SyntaxKind { text : "ASC" , id : 55u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ATTACH : SyntaxKind = SyntaxKind { text : "ATTACH" , id : 56u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#BEFORE : SyntaxKind = SyntaxKind { text : "BEFORE" , id : 57u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#BY : SyntaxKind = SyntaxKind { text : "BY" , id : 58u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#CASCADE : SyntaxKind = SyntaxKind { text : "CASCADE" , id : 59u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#CAST : SyntaxKind = SyntaxKind { text : "CAST" , id : 60u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#CONFLICT : SyntaxKind = SyntaxKind { text : "CONFLICT" , id : 61u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#DATABASE : SyntaxKind = SyntaxKind { text : "DATABASE" , id : 62u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#DESC : SyntaxKind = SyntaxKind { text : "DESC" , id : 63u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#DETACH : SyntaxKind = SyntaxKind { text : "DETACH" , id : 64u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#EACH : SyntaxKind = SyntaxKind { text : "EACH" , id : 65u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#FAIL : SyntaxKind = SyntaxKind { text : "FAIL" , id : 66u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#OR : SyntaxKind = SyntaxKind { text : "OR" , id : 67u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#AND : SyntaxKind = SyntaxKind { text : "AND" , id : 68u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#IS : SyntaxKind = SyntaxKind { text : "IS" , id : 69u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ISNOT : SyntaxKind = SyntaxKind { text : "ISNOT" , id : 70u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#MATCH : SyntaxKind = SyntaxKind { text : "MATCH" , id : 71u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#LIKE_KW : SyntaxKind = SyntaxKind { text : "LIKE_KW" , id : 72u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#BETWEEN : SyntaxKind = SyntaxKind { text : "BETWEEN" , id : 73u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#IN : SyntaxKind = SyntaxKind { text : "IN" , id : 74u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ISNULL : SyntaxKind = SyntaxKind { text : "ISNULL" , id : 75u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#NOTNULL : SyntaxKind = SyntaxKind { text : "NOTNULL" , id : 76u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#NE : SyntaxKind = SyntaxKind { text : "NE" , id : 77u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#EQ : SyntaxKind = SyntaxKind { text : "EQ" , id : 78u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#GT : SyntaxKind = SyntaxKind { text : "GT" , id : 79u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#LE : SyntaxKind = SyntaxKind { text : "LE" , id : 80u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#LT : SyntaxKind = SyntaxKind { text : "LT" , id : 81u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#GE : SyntaxKind = SyntaxKind { text : "GE" , id : 82u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ESCAPE : SyntaxKind = SyntaxKind { text : "ESCAPE" , id : 83u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ID : SyntaxKind = SyntaxKind { text : "ID" , id : 84u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#COLUMNKW : SyntaxKind = SyntaxKind { text : "COLUMNKW" , id : 85u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#DO : SyntaxKind = SyntaxKind { text : "DO" , id : 86u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#FOR : SyntaxKind = SyntaxKind { text : "FOR" , id : 87u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#IGNORE : SyntaxKind = SyntaxKind { text : "IGNORE" , id : 88u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#INITIALLY : SyntaxKind = SyntaxKind { text : "INITIALLY" , id : 89u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#INSTEAD : SyntaxKind = SyntaxKind { text : "INSTEAD" , id : 90u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#NO : SyntaxKind = SyntaxKind { text : "NO" , id : 91u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#KEY : SyntaxKind = SyntaxKind { text : "KEY" , id : 92u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#OF : SyntaxKind = SyntaxKind { text : "OF" , id : 93u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#OFFSET : SyntaxKind = SyntaxKind { text : "OFFSET" , id : 94u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#PRAGMA : SyntaxKind = SyntaxKind { text : "PRAGMA" , id : 95u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#RAISE : SyntaxKind = SyntaxKind { text : "RAISE" , id : 96u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#RECURSIVE : SyntaxKind = SyntaxKind { text : "RECURSIVE" , id : 97u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#REPLACE : SyntaxKind = SyntaxKind { text : "REPLACE" , id : 98u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#RESTRICT : SyntaxKind = SyntaxKind { text : "RESTRICT" , id : 99u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ROW : SyntaxKind = SyntaxKind { text : "ROW" , id : 100u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ROWS : SyntaxKind = SyntaxKind { text : "ROWS" , id : 101u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#TRIGGER : SyntaxKind = SyntaxKind { text : "TRIGGER" , id : 102u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#VACUUM : SyntaxKind = SyntaxKind { text : "VACUUM" , id : 103u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#VIEW : SyntaxKind = SyntaxKind { text : "VIEW" , id : 104u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#VIRTUAL : SyntaxKind = SyntaxKind { text : "VIRTUAL" , id : 105u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#WITH : SyntaxKind = SyntaxKind { text : "WITH" , id : 106u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#NULLS : SyntaxKind = SyntaxKind { text : "NULLS" , id : 107u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#FIRST : SyntaxKind = SyntaxKind { text : "FIRST" , id : 108u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#LAST : SyntaxKind = SyntaxKind { text : "LAST" , id : 109u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#CURRENT : SyntaxKind = SyntaxKind { text : "CURRENT" , id : 110u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#FOLLOWING : SyntaxKind = SyntaxKind { text : "FOLLOWING" , id : 111u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#PARTITION : SyntaxKind = SyntaxKind { text : "PARTITION" , id : 112u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#PRECEDING : SyntaxKind = SyntaxKind { text : "PRECEDING" , id : 113u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#RANGE : SyntaxKind = SyntaxKind { text : "RANGE" , id : 114u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#UNBOUNDED : SyntaxKind = SyntaxKind { text : "UNBOUNDED" , id : 115u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#EXCLUDE : SyntaxKind = SyntaxKind { text : "EXCLUDE" , id : 116u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#GROUPS : SyntaxKind = SyntaxKind { text : "GROUPS" , id : 117u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#OTHERS : SyntaxKind = SyntaxKind { text : "OTHERS" , id : 118u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#TIES : SyntaxKind = SyntaxKind { text : "TIES" , id : 119u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#GENERATED : SyntaxKind = SyntaxKind { text : "GENERATED" , id : 120u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ALWAYS : SyntaxKind = SyntaxKind { text : "ALWAYS" , id : 121u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#MATERIALIZED : SyntaxKind = SyntaxKind { text : "MATERIALIZED" , id : 122u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#REINDEX : SyntaxKind = SyntaxKind { text : "REINDEX" , id : 123u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#RENAME : SyntaxKind = SyntaxKind { text : "RENAME" , id : 124u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#CTIME_KW : SyntaxKind = SyntaxKind { text : "CTIME_KW" , id : 125u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ANY : SyntaxKind = SyntaxKind { text : "ANY" , id : 126u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#BITAND : SyntaxKind = SyntaxKind { text : "BITAND" , id : 127u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#BITOR : SyntaxKind = SyntaxKind { text : "BITOR" , id : 128u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#LSHIFT : SyntaxKind = SyntaxKind { text : "LSHIFT" , id : 129u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#RSHIFT : SyntaxKind = SyntaxKind { text : "RSHIFT" , id : 130u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#PLUS : SyntaxKind = SyntaxKind { text : "PLUS" , id : 131u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#MINUS : SyntaxKind = SyntaxKind { text : "MINUS" , id : 132u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#STAR : SyntaxKind = SyntaxKind { text : "STAR" , id : 133u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#SLASH : SyntaxKind = SyntaxKind { text : "SLASH" , id : 134u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#REM : SyntaxKind = SyntaxKind { text : "REM" , id : 135u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#CONCAT : SyntaxKind = SyntaxKind { text : "CONCAT" , id : 136u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#PTR : SyntaxKind = SyntaxKind { text : "PTR" , id : 137u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#COLLATE : SyntaxKind = SyntaxKind { text : "COLLATE" , id : 138u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#BITNOT : SyntaxKind = SyntaxKind { text : "BITNOT" , id : 139u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ON : SyntaxKind = SyntaxKind { text : "ON" , id : 140u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#id : SyntaxKind = SyntaxKind { text : "id" , id : 141u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#INDEXED : SyntaxKind = SyntaxKind { text : "INDEXED" , id : 142u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ids : SyntaxKind = SyntaxKind { text : "ids" , id : 143u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#STRING : SyntaxKind = SyntaxKind { text : "STRING" , id : 144u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#idj : SyntaxKind = SyntaxKind { text : "idj" , id : 145u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#JOIN_KW : SyntaxKind = SyntaxKind { text : "JOIN_KW" , id : 146u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#typename : SyntaxKind = SyntaxKind { text : "typename" , id : 147u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#signed : SyntaxKind = SyntaxKind { text : "signed" , id : 148u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#plus_num : SyntaxKind = SyntaxKind { text : "plus_num" , id : 149u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#minus_num : SyntaxKind = SyntaxKind { text : "minus_num" , id : 150u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#scanpt : SyntaxKind = SyntaxKind { text : "scanpt" , id : 151u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#scantok : SyntaxKind = SyntaxKind { text : "scantok" , id : 152u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#ccons : SyntaxKind = SyntaxKind { text : "ccons" , id : 153u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#CONSTRAINT : SyntaxKind = SyntaxKind { text : "CONSTRAINT" , id : 154u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#DEFAULT : SyntaxKind = SyntaxKind { text : "DEFAULT" , id : 155u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#term : SyntaxKind = SyntaxKind { text : "term" , id : 156u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#expr : SyntaxKind = SyntaxKind { text : "expr" , id : 157u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#NULL : SyntaxKind = SyntaxKind { text : "NULL" , id : 158u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#onconf : SyntaxKind = SyntaxKind { text : "onconf" , id : 159u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#PRIMARY : SyntaxKind = SyntaxKind { text : "PRIMARY" , id : 160u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#sortorder : SyntaxKind = SyntaxKind { text : "sortorder" , id : 161u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#autoinc : SyntaxKind = SyntaxKind { text : "autoinc" , id : 162u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#UNIQUE : SyntaxKind = SyntaxKind { text : "UNIQUE" , id : 163u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#CHECK : SyntaxKind = SyntaxKind { text : "CHECK" , id : 164u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#REFERENCES : SyntaxKind = SyntaxKind { text : "REFERENCES" , id : 165u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#eidlist_opt : SyntaxKind = SyntaxKind { text : "eidlist_opt" , id : 166u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#refargs : SyntaxKind = SyntaxKind { text : "refargs" , id : 167u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#defer_subclause : SyntaxKind = SyntaxKind { text : "defer_subclause" , id : 168u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#generated : SyntaxKind = SyntaxKind { text : "generated" , id : 169u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#AUTOINCR : SyntaxKind = SyntaxKind { text : "AUTOINCR" , id : 170u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#refarg : SyntaxKind = SyntaxKind { text : "refarg" , id : 171u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#INSERT : SyntaxKind = SyntaxKind { text : "INSERT" , id : 172u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#refact : SyntaxKind = SyntaxKind { text : "refact" , id : 173u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#DELETE : SyntaxKind = SyntaxKind { text : "DELETE" , id : 174u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#UPDATE : SyntaxKind = SyntaxKind { text : "UPDATE" , id : 175u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#SET : SyntaxKind = SyntaxKind { text : "SET" , id : 176u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#DEFERRABLE : SyntaxKind = SyntaxKind { text : "DEFERRABLE" , id : 177u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#init_deferred_pred_opt : SyntaxKind = SyntaxKind { text : "init_deferred_pred_opt" , id : 178u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#conslist : SyntaxKind = SyntaxKind { text : "conslist" , id : 179u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#tconscomma : SyntaxKind = SyntaxKind { text : "tconscomma" , id : 180u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#tcons : SyntaxKind = SyntaxKind { text : "tcons" , id : 181u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#sortlist : SyntaxKind = SyntaxKind { text : "sortlist" , id : 182u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#FOREIGN : SyntaxKind = SyntaxKind { text : "FOREIGN" , id : 183u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#eidlist : SyntaxKind = SyntaxKind { text : "eidlist" , id : 184u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#defer_subclause_opt : SyntaxKind = SyntaxKind { text : "defer_subclause_opt" , id : 185u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#orconf : SyntaxKind = SyntaxKind { text : "orconf" , id : 186u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#resolvetype : SyntaxKind = SyntaxKind { text : "resolvetype" , id : 187u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#raisetype : SyntaxKind = SyntaxKind { text : "raisetype" , id : 188u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#DROP : SyntaxKind = SyntaxKind { text : "DROP" , id : 189u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ifexists : SyntaxKind = SyntaxKind { text : "ifexists" , id : 190u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#fullname : SyntaxKind = SyntaxKind { text : "fullname" , id : 191u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#selectnowith : SyntaxKind = SyntaxKind { text : "selectnowith" , id : 192u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#oneselect : SyntaxKind = SyntaxKind { text : "oneselect" , id : 193u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#wqlist : SyntaxKind = SyntaxKind { text : "wqlist" , id : 194u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#multiselect_op : SyntaxKind = SyntaxKind { text : "multiselect_op" , id : 195u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#UNION : SyntaxKind = SyntaxKind { text : "UNION" , id : 196u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ALL : SyntaxKind = SyntaxKind { text : "ALL" , id : 197u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#EXCEPT : SyntaxKind = SyntaxKind { text : "EXCEPT" , id : 198u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#INTERSECT : SyntaxKind = SyntaxKind { text : "INTERSECT" , id : 199u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#SELECT : SyntaxKind = SyntaxKind { text : "SELECT" , id : 200u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#distinct : SyntaxKind = SyntaxKind { text : "distinct" , id : 201u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#selcollist : SyntaxKind = SyntaxKind { text : "selcollist" , id : 202u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#from : SyntaxKind = SyntaxKind { text : "from" , id : 203u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#where_opt : SyntaxKind = SyntaxKind { text : "where_opt" , id : 204u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#groupby_opt : SyntaxKind = SyntaxKind { text : "groupby_opt" , id : 205u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#having_opt : SyntaxKind = SyntaxKind { text : "having_opt" , id : 206u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#orderby_opt : SyntaxKind = SyntaxKind { text : "orderby_opt" , id : 207u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#limit_opt : SyntaxKind = SyntaxKind { text : "limit_opt" , id : 208u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#window_clause : SyntaxKind = SyntaxKind { text : "window_clause" , id : 209u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#values : SyntaxKind = SyntaxKind { text : "values" , id : 210u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#VALUES : SyntaxKind = SyntaxKind { text : "VALUES" , id : 211u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#nexprlist : SyntaxKind = SyntaxKind { text : "nexprlist" , id : 212u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#mvalues : SyntaxKind = SyntaxKind { text : "mvalues" , id : 213u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#DISTINCT : SyntaxKind = SyntaxKind { text : "DISTINCT" , id : 214u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#sclp : SyntaxKind = SyntaxKind { text : "sclp" , id : 215u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#as : SyntaxKind = SyntaxKind { text : "as" , id : 216u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#DOT : SyntaxKind = SyntaxKind { text : "DOT" , id : 217u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#seltablist : SyntaxKind = SyntaxKind { text : "seltablist" , id : 218u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#stl_prefix : SyntaxKind = SyntaxKind { text : "stl_prefix" , id : 219u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#FROM : SyntaxKind = SyntaxKind { text : "FROM" , id : 220u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#joinop : SyntaxKind = SyntaxKind { text : "joinop" , id : 221u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#on_using : SyntaxKind = SyntaxKind { text : "on_using" , id : 222u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#indexed_by : SyntaxKind = SyntaxKind { text : "indexed_by" , id : 223u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#exprlist : SyntaxKind = SyntaxKind { text : "exprlist" , id : 224u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#xfullname : SyntaxKind = SyntaxKind { text : "xfullname" , id : 225u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#JOIN : SyntaxKind = SyntaxKind { text : "JOIN" , id : 226u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#USING : SyntaxKind = SyntaxKind { text : "USING" , id : 227u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#idlist : SyntaxKind = SyntaxKind { text : "idlist" , id : 228u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#indexed_opt : SyntaxKind = SyntaxKind { text : "indexed_opt" , id : 229u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#ORDER : SyntaxKind = SyntaxKind { text : "ORDER" , id : 230u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#nulls : SyntaxKind = SyntaxKind { text : "nulls" , id : 231u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#GROUP : SyntaxKind = SyntaxKind { text : "GROUP" , id : 232u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#HAVING : SyntaxKind = SyntaxKind { text : "HAVING" , id : 233u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#LIMIT : SyntaxKind = SyntaxKind { text : "LIMIT" , id : 234u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#with : SyntaxKind = SyntaxKind { text : "with" , id : 235u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#where_opt_ret : SyntaxKind = SyntaxKind { text : "where_opt_ret" , id : 236u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#WHERE : SyntaxKind = SyntaxKind { text : "WHERE" , id : 237u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#RETURNING : SyntaxKind = SyntaxKind { text : "RETURNING" , id : 238u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#setlist : SyntaxKind = SyntaxKind { text : "setlist" , id : 239u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#insert_cmd : SyntaxKind = SyntaxKind { text : "insert_cmd" , id : 240u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#INTO : SyntaxKind = SyntaxKind { text : "INTO" , id : 241u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#idlist_opt : SyntaxKind = SyntaxKind { text : "idlist_opt" , id : 242u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#upsert : SyntaxKind = SyntaxKind { text : "upsert" , id : 243u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#returning : SyntaxKind = SyntaxKind { text : "returning" , id : 244u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#NOTHING : SyntaxKind = SyntaxKind { text : "NOTHING" , id : 245u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#FLOAT : SyntaxKind = SyntaxKind { text : "FLOAT" , id : 246u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#BLOB : SyntaxKind = SyntaxKind { text : "BLOB" , id : 247u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#INTEGER : SyntaxKind = SyntaxKind { text : "INTEGER" , id : 248u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#VARIABLE : SyntaxKind = SyntaxKind { text : "VARIABLE" , id : 249u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#filter_over : SyntaxKind = SyntaxKind { text : "filter_over" , id : 250u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#likeop : SyntaxKind = SyntaxKind { text : "likeop" , id : 251u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#between_op : SyntaxKind = SyntaxKind { text : "between_op" , id : 252u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#in_op : SyntaxKind = SyntaxKind { text : "in_op" , id : 253u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#paren_exprlist : SyntaxKind = SyntaxKind { text : "paren_exprlist" , id : 254u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#CASE : SyntaxKind = SyntaxKind { text : "CASE" , id : 255u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#case_operand : SyntaxKind = SyntaxKind { text : "case_operand" , id : 256u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#case_exprlist : SyntaxKind = SyntaxKind { text : "case_exprlist" , id : 257u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#case_else : SyntaxKind = SyntaxKind { text : "case_else" , id : 258u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#WHEN : SyntaxKind = SyntaxKind { text : "WHEN" , id : 259u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#THEN : SyntaxKind = SyntaxKind { text : "THEN" , id : 260u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ELSE : SyntaxKind = SyntaxKind { text : "ELSE" , id : 261u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#uniqueflag : SyntaxKind = SyntaxKind { text : "uniqueflag" , id : 262u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#INDEX : SyntaxKind = SyntaxKind { text : "INDEX" , id : 263u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#collate : SyntaxKind = SyntaxKind { text : "collate" , id : 264u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#vinto : SyntaxKind = SyntaxKind { text : "vinto" , id : 265u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#nmnum : SyntaxKind = SyntaxKind { text : "nmnum" , id : 266u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#number : SyntaxKind = SyntaxKind { text : "number" , id : 267u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#trigger_decl : SyntaxKind = SyntaxKind { text : "trigger_decl" , id : 268u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#trigger_cmd_list : SyntaxKind = SyntaxKind { text : "trigger_cmd_list" , id : 269u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#trigger_time : SyntaxKind = SyntaxKind { text : "trigger_time" , id : 270u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#trigger_event : SyntaxKind = SyntaxKind { text : "trigger_event" , id : 271u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#foreach_clause : SyntaxKind = SyntaxKind { text : "foreach_clause" , id : 272u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#when_clause : SyntaxKind = SyntaxKind { text : "when_clause" , id : 273u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#trigger_cmd : SyntaxKind = SyntaxKind { text : "trigger_cmd" , id : 274u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#trnm : SyntaxKind = SyntaxKind { text : "trnm" , id : 275u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#tridxby : SyntaxKind = SyntaxKind { text : "tridxby" , id : 276u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#database_kw_opt : SyntaxKind = SyntaxKind { text : "database_kw_opt" , id : 277u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#key_opt : SyntaxKind = SyntaxKind { text : "key_opt" , id : 278u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#ALTER : SyntaxKind = SyntaxKind { text : "ALTER" , id : 279u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#add_column_fullname : SyntaxKind = SyntaxKind { text : "add_column_fullname" , id : 280u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#ADD : SyntaxKind = SyntaxKind { text : "ADD" , id : 281u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#kwcolumn_opt : SyntaxKind = SyntaxKind { text : "kwcolumn_opt" , id : 282u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#create_vtab : SyntaxKind = SyntaxKind { text : "create_vtab" , id : 283u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#vtabarglist : SyntaxKind = SyntaxKind { text : "vtabarglist" , id : 284u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#vtabarg : SyntaxKind = SyntaxKind { text : "vtabarg" , id : 285u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#vtabargtoken : SyntaxKind = SyntaxKind { text : "vtabargtoken" , id : 286u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#lp : SyntaxKind = SyntaxKind { text : "lp" , id : 287u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#anylist : SyntaxKind = SyntaxKind { text : "anylist" , id : 288u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#wqitem : SyntaxKind = SyntaxKind { text : "wqitem" , id : 289u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#wqas : SyntaxKind = SyntaxKind { text : "wqas" , id : 290u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#withnm : SyntaxKind = SyntaxKind { text : "withnm" , id : 291u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#windowdefn_list : SyntaxKind = SyntaxKind { text : "windowdefn_list" , id : 292u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#windowdefn : SyntaxKind = SyntaxKind { text : "windowdefn" , id : 293u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#window : SyntaxKind = SyntaxKind { text : "window" , id : 294u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#frame_opt : SyntaxKind = SyntaxKind { text : "frame_opt" , id : 295u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#part_opt : SyntaxKind = SyntaxKind { text : "part_opt" , id : 296u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#filter_clause : SyntaxKind = SyntaxKind { text : "filter_clause" , id : 297u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#over_clause : SyntaxKind = SyntaxKind { text : "over_clause" , id : 298u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#range_or_rows : SyntaxKind = SyntaxKind { text : "range_or_rows" , id : 299u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#frame_bound : SyntaxKind = SyntaxKind { text : "frame_bound" , id : 300u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#frame_bound_s : SyntaxKind = SyntaxKind { text : "frame_bound_s" , id : 301u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#frame_bound_e : SyntaxKind = SyntaxKind { text : "frame_bound_e" , id : 302u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#frame_exclude_opt : SyntaxKind = SyntaxKind { text : "frame_exclude_opt" , id : 303u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#frame_exclude : SyntaxKind = SyntaxKind { text : "frame_exclude" , id : 304u32 , is_keyword : false , is_terminal : false } ;
  # [allow (non_upper_case_globals)] pub static r#WINDOW : SyntaxKind = SyntaxKind { text : "WINDOW" , id : 305u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#OVER : SyntaxKind = SyntaxKind { text : "OVER" , id : 306u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#FILTER : SyntaxKind = SyntaxKind { text : "FILTER" , id : 307u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#COLUMN : SyntaxKind = SyntaxKind { text : "COLUMN" , id : 308u32 , is_keyword : true , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#AGG_FUNCTION : SyntaxKind = SyntaxKind { text : "AGG_FUNCTION" , id : 309u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#AGG_COLUMN : SyntaxKind = SyntaxKind { text : "AGG_COLUMN" , id : 310u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#TRUEFALSE : SyntaxKind = SyntaxKind { text : "TRUEFALSE" , id : 311u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#FUNCTION : SyntaxKind = SyntaxKind { text : "FUNCTION" , id : 312u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#UPLUS : SyntaxKind = SyntaxKind { text : "UPLUS" , id : 313u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#UMINUS : SyntaxKind = SyntaxKind { text : "UMINUS" , id : 314u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#TRUTH : SyntaxKind = SyntaxKind { text : "TRUTH" , id : 315u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#REGISTER : SyntaxKind = SyntaxKind { text : "REGISTER" , id : 316u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#VECTOR : SyntaxKind = SyntaxKind { text : "VECTOR" , id : 317u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#SELECT_COLUMN : SyntaxKind = SyntaxKind { text : "SELECT_COLUMN" , id : 318u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#IF_NULL_ROW : SyntaxKind = SyntaxKind { text : "IF_NULL_ROW" , id : 319u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ASTERISK : SyntaxKind = SyntaxKind { text : "ASTERISK" , id : 320u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#SPAN : SyntaxKind = SyntaxKind { text : "SPAN" , id : 321u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ERROR : SyntaxKind = SyntaxKind { text : "ERROR" , id : 322u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#QNUMBER : SyntaxKind = SyntaxKind { text : "QNUMBER" , id : 323u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#SPACE : SyntaxKind = SyntaxKind { text : "SPACE" , id : 324u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#COMMENT : SyntaxKind = SyntaxKind { text : "COMMENT" , id : 325u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#ILLEGAL : SyntaxKind = SyntaxKind { text : "ILLEGAL" , id : 326u32 , is_keyword : false , is_terminal : true } ;
  # [allow (non_upper_case_globals)] pub static r#EOF : SyntaxKind = SyntaxKind { text : "EOF" , id : 327u32 , is_keyword : false , is_terminal : true } ;
}
pub mod syntax_map {
  use super::syntax_kind::*;
  pub static SYNTAX_KIND_MAP: phf::Map<u32, &'static engine_core::SyntaxKind> = phf::phf_map!{
    1u32 => & r#input ,
    2u32 => & r#cmdlist ,
    3u32 => & r#ecmd ,
    4u32 => & r#SEMI ,
    5u32 => & r#cmdx ,
    6u32 => & r#explain ,
    7u32 => & r#EXPLAIN ,
    8u32 => & r#QUERY ,
    9u32 => & r#PLAN ,
    10u32 => & r#cmd ,
    11u32 => & r#BEGIN ,
    12u32 => & r#transtype ,
    13u32 => & r#trans_opt ,
    14u32 => & r#TRANSACTION ,
    15u32 => & r#nm ,
    16u32 => & r#DEFERRED ,
    17u32 => & r#IMMEDIATE ,
    18u32 => & r#EXCLUSIVE ,
    19u32 => & r#COMMIT ,
    20u32 => & r#END ,
    21u32 => & r#ROLLBACK ,
    22u32 => & r#savepoint_opt ,
    23u32 => & r#SAVEPOINT ,
    24u32 => & r#RELEASE ,
    25u32 => & r#TO ,
    26u32 => & r#create_table ,
    27u32 => & r#create_table_args ,
    28u32 => & r#createkw ,
    29u32 => & r#temp ,
    30u32 => & r#TABLE ,
    31u32 => & r#ifnotexists ,
    32u32 => & r#dbnm ,
    33u32 => & r#CREATE ,
    34u32 => & r#IF ,
    35u32 => & r#NOT ,
    36u32 => & r#EXISTS ,
    37u32 => & r#TEMP ,
    38u32 => & r#LP ,
    39u32 => & r#columnlist ,
    40u32 => & r#conslist_opt ,
    41u32 => & r#RP ,
    42u32 => & r#table_option_set ,
    43u32 => & r#AS ,
    44u32 => & r#select ,
    45u32 => & r#table_option ,
    46u32 => & r#COMMA ,
    47u32 => & r#WITHOUT ,
    48u32 => & r#columnname ,
    49u32 => & r#carglist ,
    50u32 => & r#typetoken ,
    51u32 => & r#ABORT ,
    52u32 => & r#ACTION ,
    53u32 => & r#AFTER ,
    54u32 => & r#ANALYZE ,
    55u32 => & r#ASC ,
    56u32 => & r#ATTACH ,
    57u32 => & r#BEFORE ,
    58u32 => & r#BY ,
    59u32 => & r#CASCADE ,
    60u32 => & r#CAST ,
    61u32 => & r#CONFLICT ,
    62u32 => & r#DATABASE ,
    63u32 => & r#DESC ,
    64u32 => & r#DETACH ,
    65u32 => & r#EACH ,
    66u32 => & r#FAIL ,
    67u32 => & r#OR ,
    68u32 => & r#AND ,
    69u32 => & r#IS ,
    70u32 => & r#ISNOT ,
    71u32 => & r#MATCH ,
    72u32 => & r#LIKE_KW ,
    73u32 => & r#BETWEEN ,
    74u32 => & r#IN ,
    75u32 => & r#ISNULL ,
    76u32 => & r#NOTNULL ,
    77u32 => & r#NE ,
    78u32 => & r#EQ ,
    79u32 => & r#GT ,
    80u32 => & r#LE ,
    81u32 => & r#LT ,
    82u32 => & r#GE ,
    83u32 => & r#ESCAPE ,
    84u32 => & r#ID ,
    85u32 => & r#COLUMNKW ,
    86u32 => & r#DO ,
    87u32 => & r#FOR ,
    88u32 => & r#IGNORE ,
    89u32 => & r#INITIALLY ,
    90u32 => & r#INSTEAD ,
    91u32 => & r#NO ,
    92u32 => & r#KEY ,
    93u32 => & r#OF ,
    94u32 => & r#OFFSET ,
    95u32 => & r#PRAGMA ,
    96u32 => & r#RAISE ,
    97u32 => & r#RECURSIVE ,
    98u32 => & r#REPLACE ,
    99u32 => & r#RESTRICT ,
    100u32 => & r#ROW ,
    101u32 => & r#ROWS ,
    102u32 => & r#TRIGGER ,
    103u32 => & r#VACUUM ,
    104u32 => & r#VIEW ,
    105u32 => & r#VIRTUAL ,
    106u32 => & r#WITH ,
    107u32 => & r#NULLS ,
    108u32 => & r#FIRST ,
    109u32 => & r#LAST ,
    110u32 => & r#CURRENT ,
    111u32 => & r#FOLLOWING ,
    112u32 => & r#PARTITION ,
    113u32 => & r#PRECEDING ,
    114u32 => & r#RANGE ,
    115u32 => & r#UNBOUNDED ,
    116u32 => & r#EXCLUDE ,
    117u32 => & r#GROUPS ,
    118u32 => & r#OTHERS ,
    119u32 => & r#TIES ,
    120u32 => & r#GENERATED ,
    121u32 => & r#ALWAYS ,
    122u32 => & r#MATERIALIZED ,
    123u32 => & r#REINDEX ,
    124u32 => & r#RENAME ,
    125u32 => & r#CTIME_KW ,
    126u32 => & r#ANY ,
    127u32 => & r#BITAND ,
    128u32 => & r#BITOR ,
    129u32 => & r#LSHIFT ,
    130u32 => & r#RSHIFT ,
    131u32 => & r#PLUS ,
    132u32 => & r#MINUS ,
    133u32 => & r#STAR ,
    134u32 => & r#SLASH ,
    135u32 => & r#REM ,
    136u32 => & r#CONCAT ,
    137u32 => & r#PTR ,
    138u32 => & r#COLLATE ,
    139u32 => & r#BITNOT ,
    140u32 => & r#ON ,
    141u32 => & r#id ,
    142u32 => & r#INDEXED ,
    143u32 => & r#ids ,
    144u32 => & r#STRING ,
    145u32 => & r#idj ,
    146u32 => & r#JOIN_KW ,
    147u32 => & r#typename ,
    148u32 => & r#signed ,
    149u32 => & r#plus_num ,
    150u32 => & r#minus_num ,
    151u32 => & r#scanpt ,
    152u32 => & r#scantok ,
    153u32 => & r#ccons ,
    154u32 => & r#CONSTRAINT ,
    155u32 => & r#DEFAULT ,
    156u32 => & r#term ,
    157u32 => & r#expr ,
    158u32 => & r#NULL ,
    159u32 => & r#onconf ,
    160u32 => & r#PRIMARY ,
    161u32 => & r#sortorder ,
    162u32 => & r#autoinc ,
    163u32 => & r#UNIQUE ,
    164u32 => & r#CHECK ,
    165u32 => & r#REFERENCES ,
    166u32 => & r#eidlist_opt ,
    167u32 => & r#refargs ,
    168u32 => & r#defer_subclause ,
    169u32 => & r#generated ,
    170u32 => & r#AUTOINCR ,
    171u32 => & r#refarg ,
    172u32 => & r#INSERT ,
    173u32 => & r#refact ,
    174u32 => & r#DELETE ,
    175u32 => & r#UPDATE ,
    176u32 => & r#SET ,
    177u32 => & r#DEFERRABLE ,
    178u32 => & r#init_deferred_pred_opt ,
    179u32 => & r#conslist ,
    180u32 => & r#tconscomma ,
    181u32 => & r#tcons ,
    182u32 => & r#sortlist ,
    183u32 => & r#FOREIGN ,
    184u32 => & r#eidlist ,
    185u32 => & r#defer_subclause_opt ,
    186u32 => & r#orconf ,
    187u32 => & r#resolvetype ,
    188u32 => & r#raisetype ,
    189u32 => & r#DROP ,
    190u32 => & r#ifexists ,
    191u32 => & r#fullname ,
    192u32 => & r#selectnowith ,
    193u32 => & r#oneselect ,
    194u32 => & r#wqlist ,
    195u32 => & r#multiselect_op ,
    196u32 => & r#UNION ,
    197u32 => & r#ALL ,
    198u32 => & r#EXCEPT ,
    199u32 => & r#INTERSECT ,
    200u32 => & r#SELECT ,
    201u32 => & r#distinct ,
    202u32 => & r#selcollist ,
    203u32 => & r#from ,
    204u32 => & r#where_opt ,
    205u32 => & r#groupby_opt ,
    206u32 => & r#having_opt ,
    207u32 => & r#orderby_opt ,
    208u32 => & r#limit_opt ,
    209u32 => & r#window_clause ,
    210u32 => & r#values ,
    211u32 => & r#VALUES ,
    212u32 => & r#nexprlist ,
    213u32 => & r#mvalues ,
    214u32 => & r#DISTINCT ,
    215u32 => & r#sclp ,
    216u32 => & r#as ,
    217u32 => & r#DOT ,
    218u32 => & r#seltablist ,
    219u32 => & r#stl_prefix ,
    220u32 => & r#FROM ,
    221u32 => & r#joinop ,
    222u32 => & r#on_using ,
    223u32 => & r#indexed_by ,
    224u32 => & r#exprlist ,
    225u32 => & r#xfullname ,
    226u32 => & r#JOIN ,
    227u32 => & r#USING ,
    228u32 => & r#idlist ,
    229u32 => & r#indexed_opt ,
    230u32 => & r#ORDER ,
    231u32 => & r#nulls ,
    232u32 => & r#GROUP ,
    233u32 => & r#HAVING ,
    234u32 => & r#LIMIT ,
    235u32 => & r#with ,
    236u32 => & r#where_opt_ret ,
    237u32 => & r#WHERE ,
    238u32 => & r#RETURNING ,
    239u32 => & r#setlist ,
    240u32 => & r#insert_cmd ,
    241u32 => & r#INTO ,
    242u32 => & r#idlist_opt ,
    243u32 => & r#upsert ,
    244u32 => & r#returning ,
    245u32 => & r#NOTHING ,
    246u32 => & r#FLOAT ,
    247u32 => & r#BLOB ,
    248u32 => & r#INTEGER ,
    249u32 => & r#VARIABLE ,
    250u32 => & r#filter_over ,
    251u32 => & r#likeop ,
    252u32 => & r#between_op ,
    253u32 => & r#in_op ,
    254u32 => & r#paren_exprlist ,
    255u32 => & r#CASE ,
    256u32 => & r#case_operand ,
    257u32 => & r#case_exprlist ,
    258u32 => & r#case_else ,
    259u32 => & r#WHEN ,
    260u32 => & r#THEN ,
    261u32 => & r#ELSE ,
    262u32 => & r#uniqueflag ,
    263u32 => & r#INDEX ,
    264u32 => & r#collate ,
    265u32 => & r#vinto ,
    266u32 => & r#nmnum ,
    267u32 => & r#number ,
    268u32 => & r#trigger_decl ,
    269u32 => & r#trigger_cmd_list ,
    270u32 => & r#trigger_time ,
    271u32 => & r#trigger_event ,
    272u32 => & r#foreach_clause ,
    273u32 => & r#when_clause ,
    274u32 => & r#trigger_cmd ,
    275u32 => & r#trnm ,
    276u32 => & r#tridxby ,
    277u32 => & r#database_kw_opt ,
    278u32 => & r#key_opt ,
    279u32 => & r#ALTER ,
    280u32 => & r#add_column_fullname ,
    281u32 => & r#ADD ,
    282u32 => & r#kwcolumn_opt ,
    283u32 => & r#create_vtab ,
    284u32 => & r#vtabarglist ,
    285u32 => & r#vtabarg ,
    286u32 => & r#vtabargtoken ,
    287u32 => & r#lp ,
    288u32 => & r#anylist ,
    289u32 => & r#wqitem ,
    290u32 => & r#wqas ,
    291u32 => & r#withnm ,
    292u32 => & r#windowdefn_list ,
    293u32 => & r#windowdefn ,
    294u32 => & r#window ,
    295u32 => & r#frame_opt ,
    296u32 => & r#part_opt ,
    297u32 => & r#filter_clause ,
    298u32 => & r#over_clause ,
    299u32 => & r#range_or_rows ,
    300u32 => & r#frame_bound ,
    301u32 => & r#frame_bound_s ,
    302u32 => & r#frame_bound_e ,
    303u32 => & r#frame_exclude_opt ,
    304u32 => & r#frame_exclude ,
    305u32 => & r#WINDOW ,
    306u32 => & r#OVER ,
    307u32 => & r#FILTER ,
    308u32 => & r#COLUMN ,
    309u32 => & r#AGG_FUNCTION ,
    310u32 => & r#AGG_COLUMN ,
    311u32 => & r#TRUEFALSE ,
    312u32 => & r#FUNCTION ,
    313u32 => & r#UPLUS ,
    314u32 => & r#UMINUS ,
    315u32 => & r#TRUTH ,
    316u32 => & r#REGISTER ,
    317u32 => & r#VECTOR ,
    318u32 => & r#SELECT_COLUMN ,
    319u32 => & r#IF_NULL_ROW ,
    320u32 => & r#ASTERISK ,
    321u32 => & r#SPAN ,
    322u32 => & r#ERROR ,
    323u32 => & r#QNUMBER ,
    324u32 => & r#SPACE ,
    325u32 => & r#COMMENT ,
    326u32 => & r#ILLEGAL ,
    327u32 => & r#EOF ,
  };
}
