package ritalin:parser@0.0.1;

interface parsers {
    /// create new parser instance
    create: func() -> parser;

    use syntaxes.{syntax-tree};
    use errors.{parse-error};

    resource parser {
        /// execute to parse souce content
        parse: func(source: string) -> syntax-tree;
    }
}

interface errors {
    variant parse-error {
        node-build-failed(string),
    }
}

interface types {
    // Terminal/Non-terminal symbol definition
    record syntax-kind {
        // symbol name
        name: string,
        // symbol group category
        group: symbol-group,
    }

    enum symbol-group { keyword, non-keyword, pattern, non-terminal }

    // Syntax node type
    enum node-type {
        node,
        // node for owning leading trivias, token and trailing trivias
        token-set,
        // leading trivia mainly has some comment
        leading-trivia,
        // main token
        token-item,
        // trailing trivia mainly has some white space
        trailing-trivia,
    }

    // error recovery type selected by a error recovery
    enum patch-action {
        // no error recovery
        none,
        // lookahead token is deleted
        delete,
        // Non-terminated symbol is inserted
        shift,
        // failed to error recovery
        invalid,
    }
}

interface syntaxes {
    use types.{syntax-kind, node-type, patch-action};

    // A syntax tree returned the parser
    resource syntax-tree {
        // Root node
        root: func() -> syntax-node;
    }

    // Syntax node is mainly Non-terminated symbol 
    resource syntax-node {
        // Node metadata key
        metadata-key: func() -> metadata-key;
        // Node metadata value
        metadata: func() -> metadata;
        // parent node
        // it will return none if not root node
        parent: func() -> option<syntax-node>;
        // all of the child nodes or the token-sets
        children: func() -> list<syntax-element>;
        // look up a item of the syntax token set
        token-at-offset: func(byte-offset: u32) -> option<syntax-token-item>;
        // get previous neighbor sibling node on the same parent
        prev-sibling: func() -> option<syntax-element>;
        // get next neighbor sibling node on the same parent
        next-sibling: func() -> option<syntax-element>;
    }

    // Token set is grouping token items
    resource syntax-token-set {
        // Node metadata key
        metadata-key: func() -> metadata-key;
        // Node metadata value
        metadata: func() -> metadata;
        // parent node
        // it will return none if not root node
        parent: func() -> option<syntax-node>;
        // get previous neighbor sibling node on the same parent
        prev-sibling: func() -> option<syntax-element>;
        // get next neighbor sibling node on the same parent
        next-sibling: func() -> option<syntax-element>;
        // Returns leading trivia tokens
        leading-trivia: func() -> list<syntax-token-item>;
        // Returns main token
        token: func() -> syntax-token-item;
        // returns trailing trivia tokens
        trailing-trivia: func() -> list<syntax-token-item>;
        // Look up another candidate for specified node or token set
        lookup-candidates: func() -> list<syntax-kind>;
    }

    resource syntax-token-item {
        // Node metadata key
        metadata-key: func() -> metadata-key;
        // Node metadata value
        metadata: func() -> metadata;
        // parent node
        // it will return none if not root node
        parent: func() -> option<syntax-token-set>;
        // get previous neighbor token over the parent node
        prev-token: func() -> option<syntax-token-item>;
        // get next neighbor token over the parent node
        next-token: func() -> option<syntax-token-item>;
        // Returns token value
        value: func() -> string;
    }

    // Children of node consists of the node or the token set 
    variant syntax-element {
        node(syntax-node),
        token-set(syntax-token-set),
    }

    record metadata-key {
        // symbol kind of node
        kind: syntax-kind,
        // byte offset from begining of the document 
        offset: u32,
        // byte-length of node
        // For the node and the token set, it's a summary of all descendant node 
        len: u32,
        // Wherther node is leaf (token item)
        is-leaf: bool,
    }

    record metadata {
        // type of node
        node-type: node-type,
        // Resume state at incremental parsing
        edit-state: u64,
        // Selected patch action
        // If it does not go to error recover, `None` passed
        patch: patch-action,
        // char offset from begining of the document 
        char-offset: u32,
        // char length of node
        // For the node and the token set, it's a summary of all descendant node 
        char-len: u32,
    }

    // Look up next candidate for specified node or token set
    // lookup-next-candidates: func(el: syntax-element) -> list<syntax-kind>;
}

world types-world {
    export types;
}

world syntax-tree-world {
    import types;
    export syntaxes;
}

world parser-world {
    export types;
    export syntaxes;
    export parsers;
}