/* automatically generated by rust-bindgen 0.71.1 */

#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals)]

unsafe extern "C" {
    pub fn sqlite3_keyword_check(
        zName: *const ::std::os::raw::c_char,
        nName: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
